// This file is auto-generated by @hey-api/openapi-ts

export const AdjustmentTargetSchema = {
    type: 'string',
    enum: ['UNIT', 'QUANTITY'],
    title: 'AdjustmentTarget'
} as const;

export const AuditEntryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger: {
            type: 'string',
            enum: ['UNIT', 'PART'],
            title: 'Ledger'
        },
        event_type: {
            '$ref': '#/components/schemas/MovementType'
        },
        occurred_at: {
            type: 'string',
            format: 'date-time',
            title: 'Occurred At'
        },
        actor_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Actor User Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        },
        sale_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sale Id'
        },
        service_ticket_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Ticket Id'
        },
        project_pull_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Pull Id'
        },
        stock_adjustment_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock Adjustment Id'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['id', 'ledger', 'event_type', 'occurred_at', 'actor_user_id', 'quantity'],
    title: 'AuditEntryPublic'
} as const;

export const BatchDrillRowSchema = {
    properties: {
        batch_no: {
            type: 'string',
            title: 'Batch No'
        },
        remaining_qty: {
            type: 'integer',
            title: 'Remaining Qty'
        },
        received_at: {
            type: 'string',
            format: 'date-time',
            title: 'Received At'
        }
    },
    type: 'object',
    required: ['batch_no', 'remaining_qty', 'received_at'],
    title: 'BatchDrillRow'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BulkMinStockItemSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        min_stock_level: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000000,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Stock Level'
        }
    },
    type: 'object',
    required: ['product_id'],
    title: 'BulkMinStockItem'
} as const;

export const BulkMinStockUpdateSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/BulkMinStockItem'
            },
            type: 'array',
            maxItems: 500,
            minItems: 1,
            title: 'Items'
        }
    },
    type: 'object',
    required: ['items'],
    title: 'BulkMinStockUpdate'
} as const;

export const ChannelSchema = {
    type: 'string',
    enum: ['SALE', 'MAINTENANCE', 'PROJECT'],
    title: 'Channel'
} as const;

export const ChannelMarginReportSchema = {
    properties: {
        month: {
            type: 'string',
            title: 'Month'
        },
        channels: {
            items: {
                '$ref': '#/components/schemas/ChannelMarginRow'
            },
            type: 'array',
            title: 'Channels'
        },
        total_revenue_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,12}|(?=[\\d.]{1,15}0*$)\\d{0,12}\\.\\d{0,2}0*$)',
            title: 'Total Revenue Thb'
        },
        total_cogs_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,12}|(?=[\\d.]{1,15}0*$)\\d{0,12}\\.\\d{0,2}0*$)',
            title: 'Total Cogs Thb'
        },
        total_margin_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,12}|(?=[\\d.]{1,15}0*$)\\d{0,12}\\.\\d{0,2}0*$)',
            title: 'Total Margin Thb'
        }
    },
    type: 'object',
    required: ['month', 'channels', 'total_revenue_thb', 'total_cogs_thb', 'total_margin_thb'],
    title: 'ChannelMarginReport'
} as const;

export const ChannelMarginRowSchema = {
    properties: {
        channel: {
            '$ref': '#/components/schemas/Channel'
        },
        revenue_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,12}|(?=[\\d.]{1,15}0*$)\\d{0,12}\\.\\d{0,2}0*$)',
            title: 'Revenue Thb'
        },
        cogs_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,12}|(?=[\\d.]{1,15}0*$)\\d{0,12}\\.\\d{0,2}0*$)',
            title: 'Cogs Thb'
        },
        margin_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,12}|(?=[\\d.]{1,15}0*$)\\d{0,12}\\.\\d{0,2}0*$)',
            title: 'Margin Thb'
        }
    },
    type: 'object',
    required: ['channel', 'revenue_thb', 'cogs_thb', 'margin_thb'],
    title: 'ChannelMarginRow'
} as const;

export const CustomerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        type: {
            '$ref': '#/components/schemas/CustomerType',
            default: 'END_CUSTOMER'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CustomerCreate'
} as const;

export const CustomerDashboardAdminPublicSchema = {
    properties: {
        customer: {
            '$ref': '#/components/schemas/CustomerPublic'
        },
        transactions: {
            items: {
                '$ref': '#/components/schemas/TransactionSummaryPublic'
            },
            type: 'array',
            title: 'Transactions'
        },
        active_projects: {
            items: {
                '$ref': '#/components/schemas/ProjectSummaryAdminPublic'
            },
            type: 'array',
            title: 'Active Projects'
        },
        closed_projects: {
            items: {
                '$ref': '#/components/schemas/ProjectSummaryAdminPublic'
            },
            type: 'array',
            title: 'Closed Projects'
        },
        lifetime_sale_revenue_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Lifetime Sale Revenue Thb'
        },
        lifetime_sale_cogs_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Lifetime Sale Cogs Thb'
        },
        lifetime_sale_margin_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Lifetime Sale Margin Thb'
        },
        lifetime_maintenance_revenue_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Lifetime Maintenance Revenue Thb'
        },
        lifetime_maintenance_cogs_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Lifetime Maintenance Cogs Thb'
        },
        lifetime_maintenance_margin_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Lifetime Maintenance Margin Thb'
        },
        lifetime_project_cogs_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Lifetime Project Cogs Thb'
        }
    },
    type: 'object',
    required: ['customer', 'transactions', 'active_projects', 'closed_projects', 'lifetime_sale_revenue_thb', 'lifetime_sale_cogs_thb', 'lifetime_sale_margin_thb', 'lifetime_maintenance_revenue_thb', 'lifetime_maintenance_cogs_thb', 'lifetime_maintenance_margin_thb', 'lifetime_project_cogs_thb'],
    title: 'CustomerDashboardAdminPublic'
} as const;

export const CustomerDashboardStaffPublicSchema = {
    properties: {
        customer: {
            '$ref': '#/components/schemas/CustomerPublic'
        },
        transactions: {
            items: {
                '$ref': '#/components/schemas/TransactionSummaryPublic'
            },
            type: 'array',
            title: 'Transactions'
        },
        active_projects: {
            items: {
                '$ref': '#/components/schemas/ProjectSummaryStaffPublic'
            },
            type: 'array',
            title: 'Active Projects'
        },
        closed_projects: {
            items: {
                '$ref': '#/components/schemas/ProjectSummaryStaffPublic'
            },
            type: 'array',
            title: 'Closed Projects'
        }
    },
    type: 'object',
    required: ['customer', 'transactions', 'active_projects', 'closed_projects'],
    title: 'CustomerDashboardStaffPublic'
} as const;

export const CustomerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        type: {
            '$ref': '#/components/schemas/CustomerType',
            default: 'END_CUSTOMER'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'CustomerPublic'
} as const;

export const CustomerTypeSchema = {
    type: 'string',
    enum: ['DEALER', 'END_CUSTOMER'],
    title: 'CustomerType'
} as const;

export const CustomerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CustomerType'
                },
                {
                    type: 'null'
                }
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CustomerUpdate'
} as const;

export const ExchangeRatesPublicSchema = {
    properties: {
        usd_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Usd Thb'
        },
        mmk_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Mmk Thb'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['usd_thb', 'mmk_thb'],
    title: 'ExchangeRatesPublic'
} as const;

export const ExchangeRatesUpdateSchema = {
    properties: {
        usd_thb: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1000000,
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Usd Thb'
        },
        mmk_thb: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1000000,
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Mmk Thb'
        }
    },
    type: 'object',
    required: ['usd_thb', 'mmk_thb'],
    title: 'ExchangeRatesUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HoldingPeriodReportSchema = {
    properties: {
        threshold_days: {
            type: 'integer',
            title: 'Threshold Days'
        },
        generated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Generated At'
        },
        rows: {
            items: {
                '$ref': '#/components/schemas/HoldingPeriodRow'
            },
            type: 'array',
            title: 'Rows'
        }
    },
    type: 'object',
    required: ['threshold_days', 'generated_at', 'rows'],
    title: 'HoldingPeriodReport'
} as const;

export const HoldingPeriodRowSchema = {
    properties: {
        tracking_mode: {
            '$ref': '#/components/schemas/TrackingMode'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        sku: {
            type: 'string',
            title: 'Sku'
        },
        reference: {
            type: 'string',
            title: 'Reference'
        },
        received_at: {
            type: 'string',
            format: 'date-time',
            title: 'Received At'
        },
        holding_days: {
            type: 'integer',
            title: 'Holding Days'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        over_threshold: {
            type: 'boolean',
            title: 'Over Threshold'
        }
    },
    type: 'object',
    required: ['tracking_mode', 'product_id', 'sku', 'reference', 'received_at', 'holding_days', 'quantity', 'over_threshold'],
    title: 'HoldingPeriodRow'
} as const;

export const LineStateSchema = {
    type: 'string',
    enum: ['PENDING', 'FULFILLED', 'SHORT', 'CANCELLED'],
    title: 'LineState'
} as const;

export const LowStockItemPublicSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        sku: {
            type: 'string',
            title: 'Sku'
        },
        model_name: {
            type: 'string',
            title: 'Model Name'
        },
        tracking_mode: {
            '$ref': '#/components/schemas/TrackingMode'
        },
        on_hand: {
            type: 'integer',
            title: 'On Hand'
        },
        min_stock_level: {
            type: 'integer',
            title: 'Min Stock Level'
        }
    },
    type: 'object',
    required: ['product_id', 'sku', 'model_name', 'tracking_mode', 'on_hand', 'min_stock_level'],
    title: 'LowStockItemPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MinStockLevelUpdateSchema = {
    properties: {
        min_stock_level: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000000,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Stock Level'
        }
    },
    type: 'object',
    title: 'MinStockLevelUpdate'
} as const;

export const MovementTypeSchema = {
    type: 'string',
    enum: ['RECEIVED', 'SOLD', 'MAINTENANCE_OUT', 'PROJECT_OUT', 'ADJUSTED_OUT'],
    title: 'MovementType'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotificationChannelSchema = {
    type: 'string',
    enum: ['LINE', 'VIBER'],
    title: 'NotificationChannel'
} as const;

export const NotificationEventSchema = {
    type: 'string',
    enum: ['LOW_STOCK', 'OVERRIDE_PENDING', 'PULL_FULFILLED', 'PULL_SHORT'],
    title: 'NotificationEvent'
} as const;

export const NotificationPreferencePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        channel: {
            '$ref': '#/components/schemas/NotificationChannel'
        },
        event_type: {
            '$ref': '#/components/schemas/NotificationEvent'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['id', 'channel', 'event_type', 'enabled'],
    title: 'NotificationPreferencePublic'
} as const;

export const NotificationPreferenceUpdateSchema = {
    properties: {
        channel: {
            '$ref': '#/components/schemas/NotificationChannel'
        },
        event_type: {
            '$ref': '#/components/schemas/NotificationEvent'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['channel', 'event_type', 'enabled'],
    title: 'NotificationPreferenceUpdate'
} as const;

export const NotificationPreferencesUpdateSchema = {
    properties: {
        preferences: {
            items: {
                '$ref': '#/components/schemas/NotificationPreferenceUpdate'
            },
            type: 'array',
            maxItems: 100,
            minItems: 1,
            title: 'Preferences'
        }
    },
    type: 'object',
    required: ['preferences'],
    title: 'NotificationPreferencesUpdate'
} as const;

export const OverrideExceptionRowSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        target_kind: {
            '$ref': '#/components/schemas/OverrideTargetKind'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        sku: {
            type: 'string',
            title: 'Sku'
        },
        default_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,12}|(?=[\\d.]{1,15}0*$)\\d{0,12}\\.\\d{0,2}0*$)',
            title: 'Default Price Thb'
        },
        requested_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,12}|(?=[\\d.]{1,15}0*$)\\d{0,12}\\.\\d{0,2}0*$)',
            title: 'Requested Price Thb'
        },
        deviation_pct: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Deviation Pct'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        },
        state: {
            '$ref': '#/components/schemas/OverrideState'
        },
        created_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        decided_by_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Decided By User Id'
        },
        decided_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Decided At'
        }
    },
    type: 'object',
    required: ['id', 'target_kind', 'product_id', 'sku', 'default_price_thb', 'requested_price_thb', 'deviation_pct', 'reason', 'state', 'created_by_user_id', 'created_at', 'decided_by_user_id', 'decided_at'],
    title: 'OverrideExceptionRow'
} as const;

export const OverrideExceptionsReportSchema = {
    properties: {
        month: {
            type: 'string',
            title: 'Month'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        auto_approved: {
            type: 'integer',
            title: 'Auto Approved'
        },
        pending: {
            type: 'integer',
            title: 'Pending'
        },
        approved: {
            type: 'integer',
            title: 'Approved'
        },
        rejected: {
            type: 'integer',
            title: 'Rejected'
        },
        rows: {
            items: {
                '$ref': '#/components/schemas/OverrideExceptionRow'
            },
            type: 'array',
            title: 'Rows'
        }
    },
    type: 'object',
    required: ['month', 'total', 'auto_approved', 'pending', 'approved', 'rejected', 'rows'],
    title: 'OverrideExceptionsReport'
} as const;

export const OverrideStateSchema = {
    type: 'string',
    enum: ['AUTO_APPROVED', 'PENDING', 'APPROVED', 'REJECTED'],
    title: 'OverrideState'
} as const;

export const OverrideTargetKindSchema = {
    type: 'string',
    enum: ['SALE_LINE', 'SERVICE_TICKET_PART'],
    title: 'OverrideTargetKind'
} as const;

export const PartBatchPublicSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        batch_no: {
            type: 'string',
            maxLength: 128,
            title: 'Batch No'
        },
        supplier_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier Id'
        },
        supplier_batch_ref: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier Batch Ref'
        },
        received_qty: {
            type: 'integer',
            title: 'Received Qty'
        },
        remaining_qty: {
            type: 'integer',
            title: 'Remaining Qty'
        },
        purchase_cost_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Purchase Cost Thb'
        },
        is_adjustment: {
            type: 'boolean',
            title: 'Is Adjustment',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        received_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Received By User Id'
        },
        received_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Received At'
        }
    },
    type: 'object',
    required: ['product_id', 'batch_no', 'received_qty', 'remaining_qty', 'purchase_cost_thb', 'id', 'received_by_user_id'],
    title: 'PartBatchPublic'
} as const;

export const PriceChangePublicSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        field: {
            type: 'string',
            maxLength: 32,
            title: 'Field'
        },
        old_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Old Value'
        },
        new_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'New Value'
        },
        reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        changed_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Changed By User Id'
        },
        changed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changed At'
        }
    },
    type: 'object',
    required: ['product_id', 'field', 'old_value', 'new_value', 'id', 'changed_by_user_id'],
    title: 'PriceChangePublic'
} as const;

export const PricingOverrideCreateSchema = {
    properties: {
        target_kind: {
            '$ref': '#/components/schemas/OverrideTargetKind'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        requested_price_thb: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 9999999999.99,
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Requested Price Thb'
        },
        reason: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['target_kind', 'product_id', 'requested_price_thb', 'reason'],
    title: 'PricingOverrideCreate'
} as const;

export const PricingOverrideDecisionSchema = {
    properties: {
        decision: {
            type: 'string',
            enum: ['APPROVED', 'REJECTED'],
            title: 'Decision'
        }
    },
    type: 'object',
    required: ['decision'],
    title: 'PricingOverrideDecision'
} as const;

export const PricingOverridePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        target_kind: {
            '$ref': '#/components/schemas/OverrideTargetKind'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        default_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Default Price Thb'
        },
        requested_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Requested Price Thb'
        },
        deviation_pct: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Deviation Pct'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        },
        state: {
            '$ref': '#/components/schemas/OverrideState'
        },
        created_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        decided_by_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Decided By User Id'
        },
        decided_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Decided At'
        }
    },
    type: 'object',
    required: ['id', 'target_kind', 'product_id', 'default_price_thb', 'requested_price_thb', 'deviation_pct', 'reason', 'state', 'created_by_user_id', 'created_at', 'decided_by_user_id', 'decided_at'],
    title: 'PricingOverridePublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'YGN_STAFF'
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProductCreateSchema = {
    properties: {
        sku: {
            type: 'string',
            maxLength: 64,
            title: 'Sku'
        },
        model_name: {
            type: 'string',
            maxLength: 255,
            title: 'Model Name'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        tracking_mode: {
            '$ref': '#/components/schemas/TrackingMode',
            default: 'QUANTITY'
        },
        specs: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specs'
        },
        retail_price_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Retail Price Thb'
        },
        repair_price_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Repair Price Thb'
        },
        default_min_stock_level: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Min Stock Level'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['sku', 'model_name', 'retail_price_thb', 'repair_price_thb'],
    title: 'ProductCreate'
} as const;

export const ProductPublicSchema = {
    properties: {
        sku: {
            type: 'string',
            maxLength: 64,
            title: 'Sku'
        },
        model_name: {
            type: 'string',
            maxLength: 255,
            title: 'Model Name'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        tracking_mode: {
            '$ref': '#/components/schemas/TrackingMode',
            default: 'QUANTITY'
        },
        specs: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specs'
        },
        retail_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Retail Price Thb'
        },
        repair_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Repair Price Thb'
        },
        default_min_stock_level: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Min Stock Level'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['sku', 'model_name', 'retail_price_thb', 'repair_price_thb', 'id'],
    title: 'ProductPublic'
} as const;

export const ProductUpdateSchema = {
    properties: {
        model_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        tracking_mode: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TrackingMode'
                },
                {
                    type: 'null'
                }
            ]
        },
        specs: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specs'
        },
        retail_price_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Retail Price Thb'
        },
        repair_price_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repair Price Thb'
        },
        default_min_stock_level: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Min Stock Level'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ProductUpdate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            title: 'Code'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            '$ref': '#/components/schemas/ProjectStatus',
            default: 'ACTIVE'
        },
        budget_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Thb'
        }
    },
    type: 'object',
    required: ['code', 'name', 'customer_id'],
    title: 'ProjectCreate'
} as const;

export const ProjectDashboardAdminPublicSchema = {
    properties: {
        project: {
            '$ref': '#/components/schemas/ProjectPublic'
        },
        pulls: {
            items: {
                '$ref': '#/components/schemas/TransactionSummaryPublic'
            },
            type: 'array',
            title: 'Pulls'
        },
        budget_thb: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Thb'
        },
        consumed_cost_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Consumed Cost Thb'
        }
    },
    type: 'object',
    required: ['project', 'pulls', 'budget_thb', 'consumed_cost_thb'],
    title: 'ProjectDashboardAdminPublic'
} as const;

export const ProjectDashboardStaffPublicSchema = {
    properties: {
        project: {
            '$ref': '#/components/schemas/ProjectStaffPublic'
        },
        pulls: {
            items: {
                '$ref': '#/components/schemas/TransactionSummaryPublic'
            },
            type: 'array',
            title: 'Pulls'
        }
    },
    type: 'object',
    required: ['project', 'pulls'],
    title: 'ProjectDashboardStaffPublic'
} as const;

export const ProjectPublicSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            title: 'Code'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            '$ref': '#/components/schemas/ProjectStatus',
            default: 'ACTIVE'
        },
        budget_thb: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Thb'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['code', 'name', 'customer_id', 'id'],
    title: 'ProjectPublic'
} as const;

export const ProjectPullCreateSchema = {
    properties: {
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        admin_notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Admin Notes'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/ProjectPullLineCreate'
            },
            type: 'array',
            maxItems: 200,
            minItems: 1,
            title: 'Lines'
        }
    },
    type: 'object',
    required: ['project_id', 'lines'],
    title: 'ProjectPullCreate'
} as const;

export const ProjectPullFulfillSchema = {
    properties: {
        lines: {
            items: {
                '$ref': '#/components/schemas/ProjectPullFulfillLine'
            },
            type: 'array',
            maxItems: 200,
            title: 'Lines'
        }
    },
    type: 'object',
    title: 'ProjectPullFulfill'
} as const;

export const ProjectPullFulfillLineSchema = {
    properties: {
        line_id: {
            type: 'string',
            format: 'uuid',
            title: 'Line Id'
        },
        fulfilled_qty: {
            type: 'integer',
            maximum: 1000000,
            minimum: 0,
            title: 'Fulfilled Qty'
        }
    },
    type: 'object',
    required: ['line_id', 'fulfilled_qty'],
    title: 'ProjectPullFulfillLine'
} as const;

export const ProjectPullLineCreateSchema = {
    properties: {
        line_kind: {
            '$ref': '#/components/schemas/SaleLineKind'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        unit_serial: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Serial'
        },
        requested_qty: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000000,
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested Qty'
        }
    },
    type: 'object',
    required: ['line_kind', 'product_id'],
    title: 'ProjectPullLineCreate'
} as const;

export const ProjectPullLinePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        line_kind: {
            '$ref': '#/components/schemas/SaleLineKind'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        unit_serial: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Serial'
        },
        requested_qty: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested Qty'
        },
        fulfilled_qty: {
            type: 'integer',
            title: 'Fulfilled Qty'
        },
        line_state: {
            '$ref': '#/components/schemas/LineState'
        }
    },
    type: 'object',
    required: ['id', 'line_kind', 'product_id', 'unit_serial', 'requested_qty', 'fulfilled_qty', 'line_state'],
    title: 'ProjectPullLinePublic'
} as const;

export const ProjectPullPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        project_name: {
            type: 'string',
            title: 'Project Name'
        },
        project_code: {
            type: 'string',
            title: 'Project Code'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        customer_name: {
            type: 'string',
            title: 'Customer Name'
        },
        state: {
            '$ref': '#/components/schemas/ProjectPullState'
        },
        admin_notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Admin Notes'
        },
        created_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        fulfilled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fulfilled At'
        },
        fulfilled_by_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fulfilled By User Id'
        },
        cancelled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cancelled At'
        },
        cancelled_by_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cancelled By User Id'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/ProjectPullLinePublic'
            },
            type: 'array',
            title: 'Lines'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'project_name', 'project_code', 'customer_id', 'customer_name', 'state', 'admin_notes', 'created_by_user_id', 'created_at', 'fulfilled_at', 'fulfilled_by_user_id', 'cancelled_at', 'cancelled_by_user_id', 'lines'],
    title: 'ProjectPullPublic'
} as const;

export const ProjectPullStateSchema = {
    type: 'string',
    enum: ['PENDING', 'FULFILLED', 'SHORT', 'CANCELLED'],
    title: 'ProjectPullState'
} as const;

export const ProjectStaffPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            '$ref': '#/components/schemas/ProjectStatus'
        }
    },
    type: 'object',
    required: ['id', 'code', 'name', 'customer_id', 'start_date', 'end_date', 'status'],
    title: 'ProjectStaffPublic'
} as const;

export const ProjectStatusSchema = {
    type: 'string',
    enum: ['ACTIVE', 'CLOSED'],
    title: 'ProjectStatus'
} as const;

export const ProjectSummaryAdminPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            '$ref': '#/components/schemas/ProjectStatus'
        },
        budget_thb: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Thb'
        },
        consumed_cost_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Consumed Cost Thb'
        }
    },
    type: 'object',
    required: ['id', 'code', 'name', 'status', 'budget_thb', 'consumed_cost_thb'],
    title: 'ProjectSummaryAdminPublic'
} as const;

export const ProjectSummaryStaffPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            '$ref': '#/components/schemas/ProjectStatus'
        }
    },
    type: 'object',
    required: ['id', 'code', 'name', 'status'],
    title: 'ProjectSummaryStaffPublic'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        customer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Id'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        budget_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Thb'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const ReceivePieceSchema = {
    properties: {
        supplier_serial: {
            type: 'string',
            maxLength: 128,
            title: 'Supplier Serial'
        },
        purchase_cost_thb: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 9999999999.99,
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Purchase Cost Thb'
        }
    },
    type: 'object',
    required: ['supplier_serial', 'purchase_cost_thb'],
    title: 'ReceivePiece'
} as const;

export const ReceiveQuantityRequestSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        supplier_id: {
            type: 'string',
            format: 'uuid',
            title: 'Supplier Id'
        },
        received_qty: {
            type: 'integer',
            maximum: 1000000,
            exclusiveMinimum: 0,
            title: 'Received Qty'
        },
        purchase_cost_thb: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 9999999999.99,
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Purchase Cost Thb'
        },
        supplier_batch_ref: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier Batch Ref'
        },
        expected_qty: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Qty'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 400
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        }
    },
    type: 'object',
    required: ['product_id', 'supplier_id', 'received_qty', 'purchase_cost_thb', 'idempotency_key'],
    title: 'ReceiveQuantityRequest'
} as const;

export const ReceiveSerializedRequestSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        supplier_id: {
            type: 'string',
            format: 'uuid',
            title: 'Supplier Id'
        },
        pieces: {
            items: {
                '$ref': '#/components/schemas/ReceivePiece'
            },
            type: 'array',
            maxItems: 500,
            minItems: 1,
            title: 'Pieces'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        }
    },
    type: 'object',
    required: ['product_id', 'supplier_id', 'pieces', 'idempotency_key'],
    title: 'ReceiveSerializedRequest'
} as const;

export const ReceiveSerializedResponseSchema = {
    properties: {
        units: {
            items: {
                '$ref': '#/components/schemas/UnitPublic'
            },
            type: 'array',
            title: 'Units'
        }
    },
    type: 'object',
    required: ['units'],
    title: 'ReceiveSerializedResponse'
} as const;

export const SaleCreateRequestSchema = {
    properties: {
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/SaleLineInput'
            },
            type: 'array',
            maxItems: 100,
            minItems: 1,
            title: 'Lines'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        }
    },
    type: 'object',
    required: ['customer_id', 'lines', 'idempotency_key'],
    title: 'SaleCreateRequest'
} as const;

export const SaleLineInputSchema = {
    properties: {
        line_kind: {
            '$ref': '#/components/schemas/SaleLineKind'
        },
        castranova_barcode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Castranova Barcode'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        quantity: {
            type: 'integer',
            maximum: 1000000,
            exclusiveMinimum: 0,
            title: 'Quantity',
            default: 1
        },
        pricing_override_request_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pricing Override Request Id'
        }
    },
    type: 'object',
    required: ['line_kind'],
    title: 'SaleLineInput'
} as const;

export const SaleLineKindSchema = {
    type: 'string',
    enum: ['UNIT', 'PART'],
    title: 'SaleLineKind'
} as const;

export const SaleLinePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        line_kind: {
            '$ref': '#/components/schemas/SaleLineKind'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        unit_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price Thb'
        },
        unit_cost_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Cost Thb'
        }
    },
    type: 'object',
    required: ['id', 'line_kind', 'unit_id', 'product_id', 'quantity', 'unit_price_thb', 'unit_cost_thb'],
    title: 'SaleLinePublic'
} as const;

export const SaleLineStaffPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        line_kind: {
            '$ref': '#/components/schemas/SaleLineKind'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        unit_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price Thb'
        }
    },
    type: 'object',
    required: ['id', 'line_kind', 'unit_id', 'product_id', 'quantity', 'unit_price_thb'],
    title: 'SaleLineStaffPublic'
} as const;

export const SalePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        total_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Thb'
        },
        total_cogs_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Cogs Thb'
        },
        sold_at: {
            type: 'string',
            format: 'date-time',
            title: 'Sold At'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/SaleLinePublic'
            },
            type: 'array',
            title: 'Lines'
        }
    },
    type: 'object',
    required: ['id', 'customer_id', 'total_thb', 'total_cogs_thb', 'sold_at', 'lines'],
    title: 'SalePublic'
} as const;

export const SaleStaffPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        total_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Thb'
        },
        sold_at: {
            type: 'string',
            format: 'date-time',
            title: 'Sold At'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/SaleLineStaffPublic'
            },
            type: 'array',
            title: 'Lines'
        }
    },
    type: 'object',
    required: ['id', 'customer_id', 'total_thb', 'sold_at', 'lines'],
    title: 'SaleStaffPublic'
} as const;

export const SerialMovementPublicSchema = {
    properties: {
        event_type: {
            '$ref': '#/components/schemas/MovementType'
        },
        from_location_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'From Location Id'
        },
        to_location_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'To Location Id'
        },
        occurred_at: {
            type: 'string',
            format: 'date-time',
            title: 'Occurred At'
        },
        actor_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Actor User Id'
        },
        sale_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sale Id'
        },
        service_ticket_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Ticket Id'
        },
        project_pull_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Pull Id'
        },
        stock_adjustment_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock Adjustment Id'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['event_type', 'from_location_id', 'to_location_id', 'occurred_at', 'actor_user_id', 'sale_id', 'service_ticket_id', 'project_pull_id', 'stock_adjustment_id', 'notes'],
    title: 'SerialMovementPublic'
} as const;

export const SerialSearchResultSchema = {
    properties: {
        castranova_barcode: {
            type: 'string',
            title: 'Castranova Barcode'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        sku: {
            type: 'string',
            title: 'Sku'
        },
        supplier_serial: {
            type: 'string',
            title: 'Supplier Serial'
        },
        current_state: {
            '$ref': '#/components/schemas/UnitState'
        },
        movements: {
            items: {
                '$ref': '#/components/schemas/SerialMovementPublic'
            },
            type: 'array',
            title: 'Movements'
        }
    },
    type: 'object',
    required: ['castranova_barcode', 'product_id', 'sku', 'supplier_serial', 'current_state', 'movements'],
    title: 'SerialSearchResult'
} as const;

export const ServiceTicketCloseSchema = {
    properties: {
        resolution: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolution'
        }
    },
    type: 'object',
    title: 'ServiceTicketClose'
} as const;

export const ServiceTicketCreateSchema = {
    properties: {
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        issue: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Issue'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        }
    },
    type: 'object',
    required: ['customer_id', 'issue', 'idempotency_key'],
    title: 'ServiceTicketCreate'
} as const;

export const ServiceTicketPartCreateSchema = {
    properties: {
        sku: {
            type: 'string',
            maxLength: 64,
            title: 'Sku'
        },
        quantity: {
            type: 'integer',
            maximum: 1000000,
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        pricing_override_request_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pricing Override Request Id'
        }
    },
    type: 'object',
    required: ['sku', 'quantity'],
    title: 'ServiceTicketPartCreate'
} as const;

export const ServiceTicketPartPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        unit_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price Thb'
        }
    },
    type: 'object',
    required: ['id', 'product_id', 'quantity', 'unit_price_thb'],
    title: 'ServiceTicketPartPublic'
} as const;

export const ServiceTicketPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        issue: {
            type: 'string',
            title: 'Issue'
        },
        resolution: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolution'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        opened_at: {
            type: 'string',
            format: 'date-time',
            title: 'Opened At'
        },
        closed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Closed At'
        },
        parts: {
            items: {
                '$ref': '#/components/schemas/ServiceTicketPartPublic'
            },
            type: 'array',
            title: 'Parts'
        }
    },
    type: 'object',
    required: ['id', 'customer_id', 'issue', 'resolution', 'notes', 'opened_at', 'closed_at', 'parts'],
    title: 'ServiceTicketPublic'
} as const;

export const SkuBatchPublicSchema = {
    properties: {
        batch_no: {
            type: 'string',
            title: 'Batch No'
        },
        received_at: {
            type: 'string',
            format: 'date-time',
            title: 'Received At'
        },
        received_qty: {
            type: 'integer',
            title: 'Received Qty'
        },
        remaining_qty: {
            type: 'integer',
            title: 'Remaining Qty'
        },
        is_adjustment: {
            type: 'boolean',
            title: 'Is Adjustment'
        }
    },
    type: 'object',
    required: ['batch_no', 'received_at', 'received_qty', 'remaining_qty', 'is_adjustment'],
    title: 'SkuBatchPublic'
} as const;

export const SkuSearchResultSchema = {
    properties: {
        sku: {
            type: 'string',
            title: 'Sku'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        tracking_mode: {
            '$ref': '#/components/schemas/TrackingMode'
        },
        total_on_hand: {
            type: 'integer',
            title: 'Total On Hand'
        },
        batches: {
            items: {
                '$ref': '#/components/schemas/SkuBatchPublic'
            },
            type: 'array',
            title: 'Batches'
        }
    },
    type: 'object',
    required: ['sku', 'product_id', 'tracking_mode', 'total_on_hand', 'batches'],
    title: 'SkuSearchResult'
} as const;

export const StockAdjustmentCreateSchema = {
    properties: {
        target_kind: {
            '$ref': '#/components/schemas/AdjustmentTarget'
        },
        castranova_barcode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Castranova Barcode'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        quantity_delta: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000000,
                    minimum: -1000000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity Delta'
        },
        purchase_cost_thb: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 9999999999.99,
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purchase Cost Thb'
        },
        reason: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Reason'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        }
    },
    type: 'object',
    required: ['target_kind', 'reason', 'idempotency_key'],
    title: 'StockAdjustmentCreate'
} as const;

export const StockAdjustmentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        target_kind: {
            '$ref': '#/components/schemas/AdjustmentTarget'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        quantity_delta: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity Delta'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        },
        created_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'target_kind', 'unit_id', 'product_id', 'quantity_delta', 'reason', 'created_by_user_id', 'created_at'],
    title: 'StockAdjustmentPublic'
} as const;

export const StockOnHandResponseSchema = {
    properties: {
        rows: {
            items: {
                '$ref': '#/components/schemas/StockOnHandRow'
            },
            type: 'array',
            title: 'Rows'
        }
    },
    type: 'object',
    required: ['rows'],
    title: 'StockOnHandResponse'
} as const;

export const StockOnHandRowSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        sku: {
            type: 'string',
            title: 'Sku'
        },
        model_name: {
            type: 'string',
            title: 'Model Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        tracking_mode: {
            '$ref': '#/components/schemas/TrackingMode'
        },
        quantity_on_hand: {
            type: 'integer',
            title: 'Quantity On Hand'
        }
    },
    type: 'object',
    required: ['product_id', 'sku', 'model_name', 'category', 'tracking_mode', 'quantity_on_hand'],
    title: 'StockOnHandRow'
} as const;

export const SupplierCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SupplierCreate'
} as const;

export const SupplierPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'SupplierPublic'
} as const;

export const SupplierUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        }
    },
    type: 'object',
    title: 'SupplierUpdate'
} as const;

export const SyncReviewItemCreateSchema = {
    properties: {
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        },
        mutation_kind: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Mutation Kind'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload'
        },
        reason: {
            '$ref': '#/components/schemas/SyncReviewReason'
        }
    },
    type: 'object',
    required: ['idempotency_key', 'mutation_kind', 'payload', 'reason'],
    title: 'SyncReviewItemCreate'
} as const;

export const SyncReviewItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        },
        mutation_kind: {
            type: 'string',
            title: 'Mutation Kind'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload'
        },
        reason: {
            '$ref': '#/components/schemas/SyncReviewReason'
        },
        state: {
            '$ref': '#/components/schemas/SyncReviewState'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        submitted_by_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Submitted By User Id'
        },
        resolved_by_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolved By User Id'
        },
        resolved_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolved At'
        },
        resolution_note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolution Note'
        }
    },
    type: 'object',
    required: ['id', 'idempotency_key', 'mutation_kind', 'payload', 'reason', 'state', 'created_at', 'submitted_by_user_id', 'resolved_by_user_id', 'resolved_at', 'resolution_note'],
    title: 'SyncReviewItemPublic'
} as const;

export const SyncReviewItemStaffPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        },
        mutation_kind: {
            type: 'string',
            title: 'Mutation Kind'
        },
        reason: {
            '$ref': '#/components/schemas/SyncReviewReason'
        },
        state: {
            '$ref': '#/components/schemas/SyncReviewState'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'idempotency_key', 'mutation_kind', 'reason', 'state', 'created_at'],
    title: 'SyncReviewItemStaffPublic'
} as const;

export const SyncReviewReasonSchema = {
    type: 'string',
    enum: ['STALE', 'CONFLICT'],
    title: 'SyncReviewReason'
} as const;

export const SyncReviewResolveSchema = {
    properties: {
        state: {
            '$ref': '#/components/schemas/SyncReviewState'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    required: ['state'],
    title: 'SyncReviewResolve'
} as const;

export const SyncReviewStateSchema = {
    type: 'string',
    enum: ['PENDING', 'RESOLVED', 'DISCARDED'],
    title: 'SyncReviewState'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TrackingModeSchema = {
    type: 'string',
    enum: ['SERIALIZED', 'QUANTITY'],
    title: 'TrackingMode'
} as const;

export const TransactionSummaryPublicSchema = {
    properties: {
        kind: {
            type: 'string',
            title: 'Kind'
        },
        reference_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reference Id'
        },
        occurred_at: {
            type: 'string',
            format: 'date-time',
            title: 'Occurred At'
        }
    },
    type: 'object',
    required: ['kind', 'reference_id', 'occurred_at'],
    title: 'TransactionSummaryPublic'
} as const;

export const UnitPublicSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        supplier_id: {
            type: 'string',
            format: 'uuid',
            title: 'Supplier Id'
        },
        supplier_serial: {
            type: 'string',
            maxLength: 128,
            title: 'Supplier Serial'
        },
        castranova_barcode: {
            type: 'string',
            maxLength: 64,
            title: 'Castranova Barcode'
        },
        current_state: {
            '$ref': '#/components/schemas/UnitState'
        },
        current_location_id: {
            type: 'string',
            format: 'uuid',
            title: 'Current Location Id'
        },
        purchase_cost_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Purchase Cost Thb'
        },
        received_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Received By User Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        received_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Received At'
        }
    },
    type: 'object',
    required: ['product_id', 'supplier_id', 'supplier_serial', 'castranova_barcode', 'current_state', 'current_location_id', 'purchase_cost_thb', 'received_by_user_id', 'id'],
    title: 'UnitPublic'
} as const;

export const UnitStateSchema = {
    type: 'string',
    enum: ['RECEIVED', 'IN_STOCK', 'SOLD', 'MAINTENANCE_OUT', 'PROJECT_OUT', 'ADJUSTED_OUT'],
    title: 'UnitState'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'YGN_STAFF'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'YGN_STAFF'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['BKK_ADMIN', 'YGN_STAFF'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'YGN_STAFF'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;