// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CustomerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        type: {
            '$ref': '#/components/schemas/CustomerType',
            default: 'END_CUSTOMER'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CustomerCreate'
} as const;

export const CustomerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        type: {
            '$ref': '#/components/schemas/CustomerType',
            default: 'END_CUSTOMER'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'CustomerPublic'
} as const;

export const CustomerTypeSchema = {
    type: 'string',
    enum: ['DEALER', 'END_CUSTOMER'],
    title: 'CustomerType'
} as const;

export const CustomerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CustomerType'
                },
                {
                    type: 'null'
                }
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CustomerUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PartBatchPublicSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        batch_no: {
            type: 'string',
            maxLength: 128,
            title: 'Batch No'
        },
        supplier_id: {
            type: 'string',
            format: 'uuid',
            title: 'Supplier Id'
        },
        supplier_batch_ref: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier Batch Ref'
        },
        received_qty: {
            type: 'integer',
            title: 'Received Qty'
        },
        remaining_qty: {
            type: 'integer',
            title: 'Remaining Qty'
        },
        purchase_cost_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Purchase Cost Thb'
        },
        is_adjustment: {
            type: 'boolean',
            title: 'Is Adjustment',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        received_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Received By User Id'
        },
        received_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Received At'
        }
    },
    type: 'object',
    required: ['product_id', 'batch_no', 'supplier_id', 'received_qty', 'remaining_qty', 'purchase_cost_thb', 'id', 'received_by_user_id'],
    title: 'PartBatchPublic'
} as const;

export const PriceChangePublicSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        field: {
            type: 'string',
            maxLength: 32,
            title: 'Field'
        },
        old_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Old Value'
        },
        new_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'New Value'
        },
        reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        changed_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Changed By User Id'
        },
        changed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changed At'
        }
    },
    type: 'object',
    required: ['product_id', 'field', 'old_value', 'new_value', 'id', 'changed_by_user_id'],
    title: 'PriceChangePublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProductCreateSchema = {
    properties: {
        sku: {
            type: 'string',
            maxLength: 64,
            title: 'Sku'
        },
        model_name: {
            type: 'string',
            maxLength: 255,
            title: 'Model Name'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        tracking_mode: {
            '$ref': '#/components/schemas/TrackingMode',
            default: 'QUANTITY'
        },
        specs: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specs'
        },
        retail_price_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Retail Price Thb'
        },
        repair_price_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Repair Price Thb'
        },
        default_min_stock_level: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Min Stock Level'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['sku', 'model_name', 'retail_price_thb', 'repair_price_thb'],
    title: 'ProductCreate'
} as const;

export const ProductPublicSchema = {
    properties: {
        sku: {
            type: 'string',
            maxLength: 64,
            title: 'Sku'
        },
        model_name: {
            type: 'string',
            maxLength: 255,
            title: 'Model Name'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        tracking_mode: {
            '$ref': '#/components/schemas/TrackingMode',
            default: 'QUANTITY'
        },
        specs: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specs'
        },
        retail_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Retail Price Thb'
        },
        repair_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Repair Price Thb'
        },
        default_min_stock_level: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Min Stock Level'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['sku', 'model_name', 'retail_price_thb', 'repair_price_thb', 'id'],
    title: 'ProductPublic'
} as const;

export const ProductUpdateSchema = {
    properties: {
        model_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        tracking_mode: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TrackingMode'
                },
                {
                    type: 'null'
                }
            ]
        },
        specs: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specs'
        },
        retail_price_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Retail Price Thb'
        },
        repair_price_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repair Price Thb'
        },
        default_min_stock_level: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Min Stock Level'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ProductUpdate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            title: 'Code'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            '$ref': '#/components/schemas/ProjectStatus',
            default: 'ACTIVE'
        },
        budget_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Thb'
        }
    },
    type: 'object',
    required: ['code', 'name', 'customer_id'],
    title: 'ProjectCreate'
} as const;

export const ProjectPublicSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            title: 'Code'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            '$ref': '#/components/schemas/ProjectStatus',
            default: 'ACTIVE'
        },
        budget_thb: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Thb'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['code', 'name', 'customer_id', 'id'],
    title: 'ProjectPublic'
} as const;

export const ProjectStatusSchema = {
    type: 'string',
    enum: ['ACTIVE', 'CLOSED'],
    title: 'ProjectStatus'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        customer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Id'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        budget_thb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Thb'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const ReceivePieceSchema = {
    properties: {
        supplier_serial: {
            type: 'string',
            maxLength: 128,
            title: 'Supplier Serial'
        },
        purchase_cost_thb: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 9999999999.99,
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Purchase Cost Thb'
        }
    },
    type: 'object',
    required: ['supplier_serial', 'purchase_cost_thb'],
    title: 'ReceivePiece'
} as const;

export const ReceiveQuantityRequestSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        supplier_id: {
            type: 'string',
            format: 'uuid',
            title: 'Supplier Id'
        },
        received_qty: {
            type: 'integer',
            maximum: 1000000,
            exclusiveMinimum: 0,
            title: 'Received Qty'
        },
        purchase_cost_thb: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 9999999999.99,
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Purchase Cost Thb'
        },
        supplier_batch_ref: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier Batch Ref'
        },
        expected_qty: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Qty'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 400
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        }
    },
    type: 'object',
    required: ['product_id', 'supplier_id', 'received_qty', 'purchase_cost_thb', 'idempotency_key'],
    title: 'ReceiveQuantityRequest'
} as const;

export const ReceiveSerializedRequestSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        supplier_id: {
            type: 'string',
            format: 'uuid',
            title: 'Supplier Id'
        },
        pieces: {
            items: {
                '$ref': '#/components/schemas/ReceivePiece'
            },
            type: 'array',
            maxItems: 500,
            minItems: 1,
            title: 'Pieces'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        }
    },
    type: 'object',
    required: ['product_id', 'supplier_id', 'pieces', 'idempotency_key'],
    title: 'ReceiveSerializedRequest'
} as const;

export const ReceiveSerializedResponseSchema = {
    properties: {
        units: {
            items: {
                '$ref': '#/components/schemas/UnitPublic'
            },
            type: 'array',
            title: 'Units'
        }
    },
    type: 'object',
    required: ['units'],
    title: 'ReceiveSerializedResponse'
} as const;

export const SaleCreateRequestSchema = {
    properties: {
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/SaleLineInput'
            },
            type: 'array',
            maxItems: 100,
            minItems: 1,
            title: 'Lines'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        }
    },
    type: 'object',
    required: ['customer_id', 'lines', 'idempotency_key'],
    title: 'SaleCreateRequest'
} as const;

export const SaleLineInputSchema = {
    properties: {
        line_kind: {
            '$ref': '#/components/schemas/SaleLineKind'
        },
        castranova_barcode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Castranova Barcode'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        quantity: {
            type: 'integer',
            maximum: 1000000,
            exclusiveMinimum: 0,
            title: 'Quantity',
            default: 1
        }
    },
    type: 'object',
    required: ['line_kind'],
    title: 'SaleLineInput'
} as const;

export const SaleLineKindSchema = {
    type: 'string',
    enum: ['UNIT', 'PART'],
    title: 'SaleLineKind'
} as const;

export const SaleLinePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        line_kind: {
            '$ref': '#/components/schemas/SaleLineKind'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        unit_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price Thb'
        },
        unit_cost_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Cost Thb'
        }
    },
    type: 'object',
    required: ['id', 'line_kind', 'unit_id', 'product_id', 'quantity', 'unit_price_thb', 'unit_cost_thb'],
    title: 'SaleLinePublic'
} as const;

export const SalePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        total_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Thb'
        },
        total_cogs_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Cogs Thb'
        },
        sold_at: {
            type: 'string',
            format: 'date-time',
            title: 'Sold At'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/SaleLinePublic'
            },
            type: 'array',
            title: 'Lines'
        }
    },
    type: 'object',
    required: ['id', 'customer_id', 'total_thb', 'total_cogs_thb', 'sold_at', 'lines'],
    title: 'SalePublic'
} as const;

export const ServiceTicketCloseSchema = {
    properties: {
        resolution: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolution'
        }
    },
    type: 'object',
    title: 'ServiceTicketClose'
} as const;

export const ServiceTicketCreateSchema = {
    properties: {
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        issue: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Issue'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        idempotency_key: {
            type: 'string',
            format: 'uuid',
            title: 'Idempotency Key'
        }
    },
    type: 'object',
    required: ['customer_id', 'issue', 'idempotency_key'],
    title: 'ServiceTicketCreate'
} as const;

export const ServiceTicketPartCreateSchema = {
    properties: {
        sku: {
            type: 'string',
            maxLength: 64,
            title: 'Sku'
        },
        quantity: {
            type: 'integer',
            maximum: 1000000,
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        unit_price_thb: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 9999999999.99,
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Price Thb'
        }
    },
    type: 'object',
    required: ['sku', 'quantity'],
    title: 'ServiceTicketPartCreate'
} as const;

export const ServiceTicketPartPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        unit_price_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price Thb'
        }
    },
    type: 'object',
    required: ['id', 'product_id', 'quantity', 'unit_price_thb'],
    title: 'ServiceTicketPartPublic'
} as const;

export const ServiceTicketPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        issue: {
            type: 'string',
            title: 'Issue'
        },
        resolution: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolution'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        opened_at: {
            type: 'string',
            format: 'date-time',
            title: 'Opened At'
        },
        closed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Closed At'
        },
        parts: {
            items: {
                '$ref': '#/components/schemas/ServiceTicketPartPublic'
            },
            type: 'array',
            title: 'Parts'
        }
    },
    type: 'object',
    required: ['id', 'customer_id', 'issue', 'resolution', 'notes', 'opened_at', 'closed_at', 'parts'],
    title: 'ServiceTicketPublic'
} as const;

export const SupplierCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SupplierCreate'
} as const;

export const SupplierPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'SupplierPublic'
} as const;

export const SupplierUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        }
    },
    type: 'object',
    title: 'SupplierUpdate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TrackingModeSchema = {
    type: 'string',
    enum: ['SERIALIZED', 'QUANTITY'],
    title: 'TrackingMode'
} as const;

export const UnitPublicSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        supplier_id: {
            type: 'string',
            format: 'uuid',
            title: 'Supplier Id'
        },
        supplier_serial: {
            type: 'string',
            maxLength: 128,
            title: 'Supplier Serial'
        },
        castranova_barcode: {
            type: 'string',
            maxLength: 64,
            title: 'Castranova Barcode'
        },
        current_state: {
            '$ref': '#/components/schemas/UnitState'
        },
        current_location_id: {
            type: 'string',
            format: 'uuid',
            title: 'Current Location Id'
        },
        purchase_cost_thb: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Purchase Cost Thb'
        },
        received_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Received By User Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        received_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Received At'
        }
    },
    type: 'object',
    required: ['product_id', 'supplier_id', 'supplier_serial', 'castranova_barcode', 'current_state', 'current_location_id', 'purchase_cost_thb', 'received_by_user_id', 'id'],
    title: 'UnitPublic'
} as const;

export const UnitStateSchema = {
    type: 'string',
    enum: ['RECEIVED', 'IN_STOCK', 'SOLD', 'MAINTENANCE_OUT', 'PROJECT_OUT', 'ADJUSTED_OUT'],
    title: 'UnitState'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'BKK_ADMIN'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'BKK_ADMIN'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['BKK_ADMIN', 'YGN_STAFF'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'BKK_ADMIN'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;