// This file is auto-generated by @hey-api/openapi-ts

export type AdjustmentTarget = 'UNIT' | 'QUANTITY';

export type AuditEntryPublic = {
    id: string;
    ledger: 'UNIT' | 'PART';
    event_type: MovementType;
    occurred_at: string;
    actor_user_id: string;
    quantity: number;
    product_id?: (string | null);
    unit_id?: (string | null);
    sale_id?: (string | null);
    service_ticket_id?: (string | null);
    project_pull_id?: (string | null);
    stock_adjustment_id?: (string | null);
    notes?: (string | null);
    product_model_name?: (string | null);
    product_sku?: (string | null);
    unit_castranova_barcode?: (string | null);
    unit_supplier_serial?: (string | null);
    customer_name?: (string | null);
    actor_full_name?: (string | null);
};

export type ledger = 'UNIT' | 'PART';

export type AuditPublic = {
    data: Array<AuditEntryPublic>;
    count: number;
};

export type BatchDrillRow = {
    batch_no: string;
    remaining_qty: number;
    received_at: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BulkMinStockItem = {
    product_id: string;
    min_stock_level?: (number | null);
};

export type BulkMinStockUpdate = {
    items: Array<BulkMinStockItem>;
};

export type Channel = 'SALE' | 'MAINTENANCE' | 'PROJECT';

export type CustomerCreate = {
    name: string;
    country?: (string | null);
    contact?: (string | null);
    type?: CustomerType;
    notes?: (string | null);
};

export type CustomerDashboardAdminPublic = {
    customer: CustomerPublic;
    transactions: Array<TransactionSummaryPublic>;
    active_projects: Array<ProjectSummaryAdminPublic>;
    closed_projects: Array<ProjectSummaryAdminPublic>;
    lifetime_sale_revenue_thb: string;
    lifetime_sale_cogs_thb: string;
    lifetime_sale_margin_thb: string;
    lifetime_maintenance_revenue_thb: string;
    lifetime_maintenance_cogs_thb: string;
    lifetime_maintenance_margin_thb: string;
    lifetime_project_cogs_thb: string;
};

export type CustomerDashboardStaffPublic = {
    customer: CustomerPublic;
    transactions: Array<TransactionSummaryPublic>;
    active_projects: Array<ProjectSummaryStaffPublic>;
    closed_projects: Array<ProjectSummaryStaffPublic>;
};

export type CustomerOption = {
    id: string;
    name: string;
};

export type CustomerPublic = {
    name: string;
    country?: (string | null);
    contact?: (string | null);
    type?: CustomerType;
    notes?: (string | null);
    id: string;
};

export type CustomersPublic = {
    data: Array<CustomerPublic>;
    count: number;
};

export type CustomerType = 'DEALER' | 'END_CUSTOMER';

export type CustomerUpdate = {
    name?: (string | null);
    country?: (string | null);
    contact?: (string | null);
    type?: (CustomerType | null);
    notes?: (string | null);
};

export type HoldingPeriodReport = {
    threshold_days: number;
    generated_at: string;
    rows: Array<HoldingPeriodRow>;
};

export type HoldingPeriodRow = {
    tracking_mode: TrackingMode;
    product_id: string;
    sku: string;
    reference: string;
    received_at: string;
    holding_days: number;
    quantity: number;
    over_threshold: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LineState = 'PENDING' | 'FULFILLED' | 'SHORT' | 'CANCELLED';

export type LowStockItemPublic = {
    product_id: string;
    sku: string;
    model_name: string;
    tracking_mode: TrackingMode;
    on_hand: number;
    min_stock_level: number;
};

export type MarginBreakdownReport = {
    month: string;
    group_by: MarginDimension;
    channel: (Channel | null);
    rows: Array<MarginBreakdownRow>;
    total_revenue_thb: string;
    total_cogs_thb: string;
    total_margin_thb: string;
};

export type MarginBreakdownRow = {
    key: string;
    label: string;
    revenue_thb: string;
    cogs_thb: string;
    margin_thb: string;
};

export type MarginDimension = 'channel' | 'product' | 'customer' | 'project';

export type Message = {
    message: string;
};

export type MinStockLevelUpdate = {
    min_stock_level?: (number | null);
};

export type MovementType = 'RECEIVED' | 'SOLD' | 'MAINTENANCE_OUT' | 'PROJECT_OUT' | 'ADJUSTED_OUT';

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationChannel = 'LINE' | 'VIBER';

export type NotificationEvent = 'LOW_STOCK' | 'OVERRIDE_PENDING' | 'PULL_FULFILLED' | 'PULL_SHORT';

export type NotificationPreferencePublic = {
    id: string;
    channel: NotificationChannel;
    event_type: NotificationEvent;
    enabled: boolean;
};

export type NotificationPreferencesUpdate = {
    preferences: Array<NotificationPreferenceUpdate>;
};

export type NotificationPreferenceUpdate = {
    channel: NotificationChannel;
    event_type: NotificationEvent;
    enabled: boolean;
};

export type OverrideExceptionRow = {
    id: string;
    target_kind: OverrideTargetKind;
    product_id: string;
    sku: string;
    default_price_thb: string;
    requested_price_thb: string;
    deviation_pct: string;
    reason: string;
    state: OverrideState;
    created_by_user_id: string;
    created_at: string;
    decided_by_user_id: (string | null);
    decided_at: (string | null);
};

export type OverrideExceptionsReport = {
    month: string;
    total: number;
    auto_approved: number;
    pending: number;
    approved: number;
    rejected: number;
    rows: Array<OverrideExceptionRow>;
};

export type OverrideState = 'AUTO_APPROVED' | 'PENDING' | 'APPROVED' | 'REJECTED';

export type OverrideTargetKind = 'SALE_LINE' | 'SERVICE_TICKET_PART';

export type PartBatchPublic = {
    product_id: string;
    batch_no: string;
    supplier_id?: (string | null);
    supplier_batch_ref?: (string | null);
    received_qty: number;
    remaining_qty: number;
    purchase_cost_thb: string;
    is_adjustment?: boolean;
    id: string;
    received_by_user_id: string;
    received_at?: (string | null);
};

export type PriceChangePublic = {
    product_id: string;
    field: string;
    old_value: string;
    new_value: string;
    reason?: (string | null);
    id: string;
    changed_by_user_id: string;
    changed_at?: (string | null);
};

export type PricingOverrideCreate = {
    target_kind: OverrideTargetKind;
    product_id: string;
    requested_price_thb: (number | string);
    reason: string;
};

export type PricingOverrideDecision = {
    decision: 'APPROVED' | 'REJECTED';
};

export type decision = 'APPROVED' | 'REJECTED';

export type PricingOverridePublic = {
    id: string;
    target_kind: OverrideTargetKind;
    product_id: string;
    product_sku: string;
    default_price_thb: string;
    requested_price_thb: string;
    deviation_pct: string;
    reason: string;
    state: OverrideState;
    created_by_user_id: string;
    created_at: string;
    decided_by_user_id: (string | null);
    decided_at: (string | null);
};

export type PricingOverridesPublic = {
    data: Array<PricingOverridePublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
    role?: UserRole;
};

export type ProductCreate = {
    sku: string;
    model_name: string;
    brand?: (string | null);
    category?: (string | null);
    tracking_mode?: TrackingMode;
    specs?: ({
    [key: string]: unknown;
} | null);
    retail_price_thb: (number | string);
    repair_price_thb: (number | string);
    default_min_stock_level?: (number | null);
    is_active?: boolean;
};

/**
 * Lightweight catalog projection for pickers/lookups (audit SKU filter, sale/
 * receive/tickets/pulls product selection). Omits `specs` (JSONB) and admin-only
 * catalog fields (brand, category, default_min_stock_level); prices are included
 * because GET /products already exposes them to the same authenticated audience.
 */
export type ProductOption = {
    id: string;
    sku: string;
    model_name: string;
    tracking_mode: TrackingMode;
    retail_price_thb: string;
    repair_price_thb: string;
};

export type ProductPublic = {
    sku: string;
    model_name: string;
    brand?: (string | null);
    category?: (string | null);
    tracking_mode?: TrackingMode;
    specs?: ({
    [key: string]: unknown;
} | null);
    retail_price_thb: string;
    repair_price_thb: string;
    default_min_stock_level?: (number | null);
    is_active?: boolean;
    id: string;
};

export type ProductPurchaseCost = {
    product_id: string;
    latest_purchase_cost_thb: string;
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductUpdate = {
    model_name?: (string | null);
    brand?: (string | null);
    category?: (string | null);
    tracking_mode?: (TrackingMode | null);
    specs?: ({
    [key: string]: unknown;
} | null);
    retail_price_thb?: (number | string | null);
    repair_price_thb?: (number | string | null);
    default_min_stock_level?: (number | null);
    is_active?: (boolean | null);
};

export type ProjectCreate = {
    code: string;
    name: string;
    customer_id: string;
    start_date?: (string | null);
    end_date?: (string | null);
    status?: ProjectStatus;
    budget_thb?: (number | string | null);
};

export type ProjectDashboardAdminPublic = {
    project: ProjectPublic;
    pulls: Array<TransactionSummaryPublic>;
    budget_thb: (string | null);
    consumed_cost_thb: string;
};

export type ProjectDashboardStaffPublic = {
    project: ProjectStaffPublic;
    pulls: Array<TransactionSummaryPublic>;
};

export type ProjectOption = {
    id: string;
    code: string;
    name: string;
};

export type ProjectPublic = {
    code: string;
    name: string;
    customer_id: string;
    start_date?: (string | null);
    end_date?: (string | null);
    status?: ProjectStatus;
    budget_thb?: (string | null);
    id: string;
};

export type ProjectPullCreate = {
    project_id: string;
    admin_notes?: (string | null);
    lines: Array<ProjectPullLineCreate>;
};

export type ProjectPullFulfill = {
    lines?: Array<ProjectPullFulfillLine>;
};

export type ProjectPullFulfillLine = {
    line_id: string;
    fulfilled_qty: number;
};

export type ProjectPullLineCreate = {
    line_kind: SaleLineKind;
    product_id: string;
    unit_serial?: (string | null);
    requested_qty?: (number | null);
};

export type ProjectPullLinePublic = {
    id: string;
    line_kind: SaleLineKind;
    product_id: string;
    product_sku: string;
    model_name: string;
    unit_serial: (string | null);
    requested_qty: (number | null);
    fulfilled_qty: number;
    line_state: LineState;
};

export type ProjectPullPublic = {
    id: string;
    project_id: string;
    project_name: string;
    project_code: string;
    customer_id: string;
    customer_name: string;
    state: ProjectPullState;
    admin_notes: (string | null);
    created_by_user_id: string;
    created_at: string;
    fulfilled_at: (string | null);
    fulfilled_by_user_id: (string | null);
    cancelled_at: (string | null);
    cancelled_by_user_id: (string | null);
    lines: Array<ProjectPullLinePublic>;
};

export type ProjectPullsPublic = {
    data: Array<ProjectPullPublic>;
    count: number;
};

export type ProjectPullState = 'PENDING' | 'FULFILLED' | 'SHORT' | 'CANCELLED';

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectStaffPublic = {
    id: string;
    code: string;
    name: string;
    customer_id: string;
    start_date: (string | null);
    end_date: (string | null);
    status: ProjectStatus;
};

export type ProjectStatus = 'ACTIVE' | 'CLOSED';

export type ProjectSummaryAdminPublic = {
    id: string;
    code: string;
    name: string;
    status: ProjectStatus;
    budget_thb: (string | null);
    consumed_cost_thb: string;
};

export type ProjectSummaryStaffPublic = {
    id: string;
    code: string;
    name: string;
    status: ProjectStatus;
};

export type ProjectUpdate = {
    code?: (string | null);
    name?: (string | null);
    customer_id?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    status?: (ProjectStatus | null);
    budget_thb?: (number | string | null);
};

export type ReceivePiece = {
    supplier_serial: string;
    purchase_cost_thb: (number | string);
};

export type ReceiveQuantityRequest = {
    product_id: string;
    supplier_id: string;
    received_qty: number;
    purchase_cost_thb: (number | string);
    supplier_batch_ref?: (string | null);
    expected_qty?: (number | null);
    note?: (string | null);
    idempotency_key: string;
};

export type ReceiveSerializedRequest = {
    product_id: string;
    supplier_id: string;
    pieces: Array<ReceivePiece>;
    idempotency_key: string;
};

export type ReceiveSerializedResponse = {
    units: Array<UnitPublic>;
};

export type SaleCreateRequest = {
    customer_id: string;
    lines: Array<SaleLineInput>;
    idempotency_key: string;
};

export type SaleLineInput = {
    line_kind: SaleLineKind;
    castranova_barcode?: (string | null);
    sku?: (string | null);
    quantity?: number;
    pricing_override_request_id?: (string | null);
};

export type SaleLineKind = 'UNIT' | 'PART';

export type SaleLinePublic = {
    id: string;
    line_kind: SaleLineKind;
    unit_id: (string | null);
    product_id: (string | null);
    quantity: number;
    unit_price_thb: string;
    unit_cost_thb: string;
};

export type SaleLineStaffPublic = {
    id: string;
    line_kind: SaleLineKind;
    unit_id: (string | null);
    product_id: (string | null);
    quantity: number;
    unit_price_thb: string;
};

export type SalePublic = {
    id: string;
    customer_id: string;
    total_thb: string;
    total_cogs_thb: string;
    sold_at: string;
    lines: Array<SaleLinePublic>;
};

export type SaleStaffPublic = {
    id: string;
    customer_id: string;
    total_thb: string;
    sold_at: string;
    lines: Array<SaleLineStaffPublic>;
};

export type SerialMovementPublic = {
    event_type: MovementType;
    from_location_id: (string | null);
    to_location_id: (string | null);
    occurred_at: string;
    actor_user_id: string;
    sale_id: (string | null);
    service_ticket_id: (string | null);
    project_pull_id: (string | null);
    stock_adjustment_id: (string | null);
    notes: (string | null);
    from_location_name?: (string | null);
    to_location_name?: (string | null);
    actor_name?: (string | null);
    reference_kind?: (string | null);
    reference_label?: (string | null);
};

export type SerialSearchResult = {
    castranova_barcode: string;
    product_id: string;
    sku: string;
    supplier_serial: string;
    current_state: UnitState;
    movements: Array<SerialMovementPublic>;
};

export type ServiceTicketPartCreate = {
    sku: string;
    quantity: number;
    pricing_override_request_id?: (string | null);
};

export type ServiceTicketPartPublic = {
    id: string;
    product_id: string;
    quantity: number;
    unit_price_thb: string;
};

export type ServiceTicketPublic = {
    id: string;
    customer_id: string;
    issue: string;
    resolution: (string | null);
    notes: (string | null);
    opened_at: string;
    closed_at: (string | null);
    parts: Array<ServiceTicketPartPublic>;
};

export type ServiceTicketRecordRequest = {
    customer_id: string;
    issue: string;
    notes?: (string | null);
    resolution?: (string | null);
    idempotency_key: string;
    parts?: Array<ServiceTicketPartCreate>;
};

export type SkuBatchAdminPublic = {
    batch_no: string;
    received_at: string;
    received_qty: number;
    remaining_qty: number;
    is_adjustment: boolean;
    purchase_cost_thb: string;
};

export type SkuBatchPublic = {
    batch_no: string;
    received_at: string;
    received_qty: number;
    remaining_qty: number;
    is_adjustment: boolean;
};

/**
 * One FIFO batch draw inside a consumption event — ADMIN only (cost).
 */
export type SkuConsumptionDrawAdminPublic = {
    batch_no: string;
    quantity: number;
    unit_cost_thb: string;
    total_cost_thb: string;
};

export type SkuConsumptionEventAdminPublic = {
    event_type: MovementType;
    occurred_at: string;
    quantity: number;
    reference_kind: string;
    reference_id: string;
    customer_name?: (string | null);
    project_name?: (string | null);
    project_code?: (string | null);
    actor_name?: (string | null);
    notes?: (string | null);
    total_cost_thb: string;
    draws: Array<SkuConsumptionDrawAdminPublic>;
};

/**
 * One consuming part_movement, STAFF view — attribution only, NO cost.
 * Any NEW cost/margin field MUST go on the Admin subclass only; staff must
 * never see cost data (mirrors SaleStaffPublic).
 */
export type SkuConsumptionEventPublic = {
    event_type: MovementType;
    occurred_at: string;
    quantity: number;
    reference_kind: string;
    reference_id: string;
    customer_name?: (string | null);
    project_name?: (string | null);
    project_code?: (string | null);
    actor_name?: (string | null);
    notes?: (string | null);
};

export type SkuSearchAdminResult = {
    sku: string;
    product_id: string;
    tracking_mode: TrackingMode;
    total_on_hand: number;
    batches: Array<SkuBatchAdminPublic>;
    consumption: Array<SkuConsumptionEventAdminPublic>;
};

export type SkuSearchResult = {
    sku: string;
    product_id: string;
    tracking_mode: TrackingMode;
    total_on_hand: number;
    batches: Array<SkuBatchPublic>;
    consumption?: Array<SkuConsumptionEventPublic>;
};

export type StockAdjustmentCreate = {
    target_kind: AdjustmentTarget;
    castranova_barcode?: (string | null);
    sku?: (string | null);
    quantity_delta?: (number | null);
    purchase_cost_thb?: (number | string | null);
    reason: string;
    idempotency_key: string;
};

export type StockAdjustmentPublic = {
    id: string;
    target_kind: AdjustmentTarget;
    unit_id: (string | null);
    product_id: (string | null);
    quantity_delta: (number | null);
    reason: string;
    created_by_user_id: string;
    created_at: string;
};

export type StockOnHandResponse = {
    rows: Array<StockOnHandRow>;
};

export type StockOnHandRow = {
    product_id: string;
    sku: string;
    model_name: string;
    brand: (string | null);
    category: (string | null);
    tracking_mode: TrackingMode;
    quantity_on_hand: number;
};

export type SupplierCreate = {
    name: string;
    country?: (string | null);
    contact?: (string | null);
};

export type SupplierOption = {
    id: string;
    name: string;
};

export type SupplierPublic = {
    name: string;
    country?: (string | null);
    contact?: (string | null);
    id: string;
};

export type SuppliersPublic = {
    data: Array<SupplierPublic>;
    count: number;
};

export type SupplierUpdate = {
    name?: (string | null);
    country?: (string | null);
    contact?: (string | null);
};

export type SyncReviewItemCreate = {
    idempotency_key: string;
    mutation_kind: string;
    payload: {
        [key: string]: unknown;
    };
    reason: SyncReviewReason;
};

export type SyncReviewItemPublic = {
    id: string;
    idempotency_key: string;
    mutation_kind: string;
    payload: {
        [key: string]: unknown;
    };
    reason: SyncReviewReason;
    state: SyncReviewState;
    created_at: string;
    submitted_by_user_id: (string | null);
    resolved_by_user_id: (string | null);
    resolved_at: (string | null);
    resolution_note: (string | null);
};

export type SyncReviewItemStaffPublic = {
    id: string;
    idempotency_key: string;
    mutation_kind: string;
    reason: SyncReviewReason;
    state: SyncReviewState;
    created_at: string;
};

export type SyncReviewReason = 'STALE' | 'CONFLICT';

export type SyncReviewResolve = {
    state: SyncReviewState;
    note?: (string | null);
};

export type SyncReviewState = 'PENDING' | 'RESOLVED' | 'DISCARDED';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TrackingMode = 'SERIALIZED' | 'QUANTITY';

export type TransactionSummaryPublic = {
    kind: string;
    reference_id: string;
    occurred_at: string;
};

export type UnitDrillRow = {
    id: string;
    castranova_barcode: string;
    supplier_serial: string;
    current_state: UnitState;
    received_at: string;
};

export type UnitPublic = {
    product_id: string;
    supplier_id: string;
    supplier_serial: string;
    castranova_barcode: string;
    current_state: UnitState;
    current_location_id: string;
    purchase_cost_thb: string;
    received_by_user_id: string;
    id: string;
    received_at?: (string | null);
};

export type UnitState = 'RECEIVED' | 'IN_STOCK' | 'SOLD' | 'MAINTENANCE_OUT' | 'PROJECT_OUT' | 'ADJUSTED_OUT';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password: string;
};

/**
 * Lightweight actor projection for the audit User filter. Deliberately
 * unpaginated: no client parameter can amplify the response size. `email` is the
 * label fallback because `full_name` is nullable. Includes deactivated users,
 * whose historical movements still appear in the append-only ledgers.
 */
export type UserOption = {
    id: string;
    full_name: (string | null);
    email: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRole = 'BKK_ADMIN' | 'YGN_STAFF';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuditListAuditData = {
    /**
     * Restrict to a single acting user
     */
    actorUserId?: (string | null);
    eventType?: (MovementType | null);
    /**
     * ISO-8601 lower bound, inclusive
     */
    fromDate?: (string | null);
    limit?: number;
    /**
     * Restrict to PART entries for a product
     */
    productId?: (string | null);
    skip?: number;
    /**
     * Restrict to a product's SKU (spans UNIT + PART ledgers)
     */
    sku?: (string | null);
    /**
     * ISO-8601 upper bound, exclusive
     */
    toDate?: (string | null);
    /**
     * Restrict to UNIT entries for a unit
     */
    unitId?: (string | null);
};

export type AuditListAuditResponse = (AuditPublic);

export type CustomersReadCustomersData = {
    /**
     * Exact match on country
     */
    country?: (string | null);
    limit?: number;
    /**
     * Case-insensitive substring match on name
     */
    q?: (string | null);
    skip?: number;
    type?: (CustomerType | null);
};

export type CustomersReadCustomersResponse = (CustomersPublic);

export type CustomersCreateCustomerData = {
    requestBody: CustomerCreate;
};

export type CustomersCreateCustomerResponse = (CustomerPublic);

export type CustomersReadOptionsResponse = (Array<CustomerOption>);

export type CustomersListCountriesResponse = (Array<(string)>);

export type CustomersGetCustomerDashboardData = {
    customerId: string;
};

export type CustomersGetCustomerDashboardResponse = ((CustomerDashboardAdminPublic | CustomerDashboardStaffPublic));

export type CustomersUpdateCustomerData = {
    customerId: string;
    requestBody: CustomerUpdate;
};

export type CustomersUpdateCustomerResponse = (CustomerPublic);

export type DashboardsGetStockOnHandData = {
    category?: (string | null);
    customer?: (string | null);
    supplier?: (string | null);
};

export type DashboardsGetStockOnHandResponse = (StockOnHandResponse);

export type DashboardsGetStockOnHandBatchesData = {
    productId: string;
};

export type DashboardsGetStockOnHandBatchesResponse = (Array<BatchDrillRow>);

export type DashboardsGetStockOnHandUnitsData = {
    productId: string;
};

export type DashboardsGetStockOnHandUnitsResponse = (Array<UnitDrillRow>);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshAccessTokenResponse = (Token);

export type LoginLogoutResponse = (Message);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LowStockReadLowStockResponse = (Array<LowStockItemPublic>);

export type LowStockBulkSetMinStockLevelData = {
    requestBody: BulkMinStockUpdate;
};

export type LowStockBulkSetMinStockLevelResponse = (Array<ProductPublic>);

export type NotificationsReadNotificationPreferencesResponse = (Array<NotificationPreferencePublic>);

export type NotificationsUpdateNotificationPreferencesData = {
    requestBody: NotificationPreferencesUpdate;
};

export type NotificationsUpdateNotificationPreferencesResponse = (Array<NotificationPreferencePublic>);

export type PricingOverridesCreatePricingOverrideData = {
    requestBody: PricingOverrideCreate;
};

export type PricingOverridesCreatePricingOverrideResponse = (PricingOverridePublic);

export type PricingOverridesListPricingOverridesData = {
    limit?: number;
    skip?: number;
    state?: (OverrideState | null);
};

export type PricingOverridesListPricingOverridesResponse = (PricingOverridesPublic);

export type PricingOverridesDecidePricingOverrideData = {
    overrideId: string;
    requestBody: PricingOverrideDecision;
};

export type PricingOverridesDecidePricingOverrideResponse = (PricingOverridePublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadProductsData = {
    /**
     * Case-insensitive substring match on brand
     */
    brand?: (string | null);
    /**
     * Case-insensitive substring match on category
     */
    category?: (string | null);
    limit?: number;
    /**
     * Case-insensitive substring match on SKU or model name
     */
    q?: (string | null);
    skip?: number;
    trackingMode?: (TrackingMode | null);
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadPurchaseCostsResponse = (Array<ProductPurchaseCost>);

export type ProductsReadOptionsData = {
    activeOnly?: boolean;
};

export type ProductsReadOptionsResponse = (Array<ProductOption>);

export type ProductsReadSkuLabelData = {
    productId: string;
    qty?: number;
};

export type ProductsReadSkuLabelResponse = (unknown);

export type ProductsUpdateProductData = {
    productId: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsSetMinStockLevelData = {
    productId: string;
    requestBody: MinStockLevelUpdate;
};

export type ProductsSetMinStockLevelResponse = (ProductPublic);

export type ProductsReadPriceHistoryData = {
    productId: string;
};

export type ProductsReadPriceHistoryResponse = (Array<PriceChangePublic>);

export type ProjectPullsCreateProjectPullData = {
    requestBody: ProjectPullCreate;
};

export type ProjectPullsCreateProjectPullResponse = (ProjectPullPublic);

export type ProjectPullsReadProjectPullsData = {
    limit?: number;
    skip?: number;
    state?: (ProjectPullState | null);
};

export type ProjectPullsReadProjectPullsResponse = (ProjectPullsPublic);

export type ProjectPullsReadProjectPullData = {
    pullId: string;
};

export type ProjectPullsReadProjectPullResponse = (ProjectPullPublic);

export type ProjectPullsFulfillProjectPullData = {
    pullId: string;
    requestBody: ProjectPullFulfill;
};

export type ProjectPullsFulfillProjectPullResponse = (ProjectPullPublic);

export type ProjectPullsCancelProjectPullData = {
    pullId: string;
};

export type ProjectPullsCancelProjectPullResponse = (ProjectPullPublic);

export type ProjectsReadProjectsData = {
    /**
     * Exact customer match
     */
    customerId?: (string | null);
    limit?: number;
    /**
     * Case-insensitive substring match on code or name
     */
    q?: (string | null);
    skip?: number;
    status?: (ProjectStatus | null);
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadOptionsResponse = (Array<ProjectOption>);

export type ProjectsGetProjectDashboardData = {
    projectId: string;
};

export type ProjectsGetProjectDashboardResponse = ((ProjectDashboardAdminPublic | ProjectDashboardStaffPublic));

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ReceiptsReceiveSerializedData = {
    requestBody: ReceiveSerializedRequest;
};

export type ReceiptsReceiveSerializedResponse = (ReceiveSerializedResponse);

export type ReceiptsReceiveQuantityData = {
    requestBody: ReceiveQuantityRequest;
};

export type ReceiptsReceiveQuantityResponse = (PartBatchPublic);

export type ReceiptsReadUnitLabelData = {
    qty?: number;
    unitId: string;
};

export type ReceiptsReadUnitLabelResponse = (unknown);

export type ReportsChannelMarginData = {
    channel?: (Channel | null);
    groupBy?: MarginDimension;
    /**
     * Reporting month in YYYY-MM (year 2000-2099)
     */
    month: string;
};

export type ReportsChannelMarginResponse = (MarginBreakdownReport);

export type ReportsChannelMarginPdfData = {
    channel?: (Channel | null);
    groupBy?: MarginDimension;
    /**
     * Reporting month in YYYY-MM (year 2000-2099)
     */
    month: string;
};

export type ReportsChannelMarginPdfResponse = (unknown);

export type ReportsChannelMarginXlsxData = {
    channel?: (Channel | null);
    groupBy?: MarginDimension;
    /**
     * Reporting month in YYYY-MM (year 2000-2099)
     */
    month: string;
};

export type ReportsChannelMarginXlsxResponse = (unknown);

export type ReportsOverrideExceptionsData = {
    /**
     * Reporting month in YYYY-MM (year 2000-2099)
     */
    month: string;
};

export type ReportsOverrideExceptionsResponse = (OverrideExceptionsReport);

export type ReportsOverrideExceptionsPdfData = {
    /**
     * Reporting month in YYYY-MM (year 2000-2099)
     */
    month: string;
};

export type ReportsOverrideExceptionsPdfResponse = (unknown);

export type ReportsOverrideExceptionsXlsxData = {
    /**
     * Reporting month in YYYY-MM (year 2000-2099)
     */
    month: string;
};

export type ReportsOverrideExceptionsXlsxResponse = (unknown);

export type ReportsHoldingPeriodData = {
    overThresholdOnly?: boolean;
};

export type ReportsHoldingPeriodResponse = (HoldingPeriodReport);

export type ReportsHoldingPeriodPdfData = {
    overThresholdOnly?: boolean;
};

export type ReportsHoldingPeriodPdfResponse = (unknown);

export type ReportsHoldingPeriodXlsxData = {
    overThresholdOnly?: boolean;
};

export type ReportsHoldingPeriodXlsxResponse = (unknown);

export type SalesCreateSaleData = {
    requestBody: SaleCreateRequest;
};

export type SalesCreateSaleResponse = ((SalePublic | SaleStaffPublic));

export type SalesReadSaleReceiptData = {
    saleId: string;
};

export type SalesReadSaleReceiptResponse = (unknown);

export type SearchSearchSerialData = {
    barcode: string;
};

export type SearchSearchSerialResponse = (SerialSearchResult);

export type SearchSearchSkuData = {
    sku: string;
};

export type SearchSearchSkuResponse = ((SkuSearchAdminResult | SkuSearchResult));

export type ServiceTicketsRecordServiceTicketData = {
    requestBody: ServiceTicketRecordRequest;
};

export type ServiceTicketsRecordServiceTicketResponse = (ServiceTicketPublic);

export type ServiceTicketsReadServiceTicketData = {
    ticketId: string;
};

export type ServiceTicketsReadServiceTicketResponse = (ServiceTicketPublic);

export type StockAdjustmentsCreateStockAdjustmentData = {
    requestBody: StockAdjustmentCreate;
};

export type StockAdjustmentsCreateStockAdjustmentResponse = (StockAdjustmentPublic);

export type SuppliersReadSuppliersData = {
    /**
     * Exact match on country
     */
    country?: (string | null);
    limit?: number;
    /**
     * Case-insensitive substring match on name
     */
    q?: (string | null);
    skip?: number;
};

export type SuppliersReadSuppliersResponse = (SuppliersPublic);

export type SuppliersCreateSupplierData = {
    requestBody: SupplierCreate;
};

export type SuppliersCreateSupplierResponse = (SupplierPublic);

export type SuppliersReadOptionsResponse = (Array<SupplierOption>);

export type SuppliersListCountriesResponse = (Array<(string)>);

export type SuppliersUpdateSupplierData = {
    requestBody: SupplierUpdate;
    supplierId: string;
};

export type SuppliersUpdateSupplierResponse = (SupplierPublic);

export type SyncReviewIngestSyncReviewItemData = {
    requestBody: SyncReviewItemCreate;
};

export type SyncReviewIngestSyncReviewItemResponse = (SyncReviewItemStaffPublic);

export type SyncReviewListSyncReviewItemsData = {
    limit?: number;
    skip?: number;
    state?: (SyncReviewState | null);
};

export type SyncReviewListSyncReviewItemsResponse = (Array<SyncReviewItemPublic>);

export type SyncReviewResolveSyncReviewItemData = {
    itemId: string;
    requestBody: SyncReviewResolve;
};

export type SyncReviewResolveSyncReviewItemResponse = (SyncReviewItemPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadOptionsResponse = (Array<UserOption>);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);