"""m011 service_ticket service_ticket_part

Revision ID: 2103c84cc16e
Revises: a76d14af1bf8
Create Date: 2026-06-04 19:39:24.423110

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2103c84cc16e'
down_revision = 'a76d14af1bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serviceticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('issue', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_service_ticket_idempotency_key')
    )
    op.create_table('serviceticketpart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_ticket_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pricing_override_request_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_service_ticket_part_qty_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['serviceticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serviceticketpart_service_ticket_id'), 'serviceticketpart', ['service_ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serviceticketpart_service_ticket_id'), table_name='serviceticketpart')
    op.drop_table('serviceticketpart')
    op.drop_table('serviceticket')
    # ### end Alembic commands ###
