"""M010 sale + sale_line + unitmovement.sale_id FK

Revision ID: 339478689c73
Revises: 79e9c3acbe2f
Create Date: 2026-06-04 16:50:06.817684

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '339478689c73'
down_revision = '79e9c3acbe2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('total_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cogs_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('receipt_pdf_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_sale_idempotency_key')
    )
    op.create_index(op.f('ix_sale_idempotency_key'), 'sale', ['idempotency_key'], unique=False)
    op.create_table('saleline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('line_kind', sa.Enum('UNIT', 'PART', name='salelinekind'), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pricing_override_request_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saleline_sale_id'), 'saleline', ['sale_id'], unique=False)
    op.create_foreign_key(
        'fk_unitmovement_sale_id', 'unitmovement', 'sale', ['sale_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_unitmovement_sale_id', 'unitmovement', type_='foreignkey')
    op.drop_index(op.f('ix_saleline_sale_id'), table_name='saleline')
    op.drop_table('saleline')
    op.drop_index(op.f('ix_sale_idempotency_key'), table_name='sale')
    op.drop_table('sale')
    # CREATE TABLE auto-created this enum; drop it so re-upgrade does not collide.
    sa.Enum(name='salelinekind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
