"""m016 part_movement append-only quantity ledger

Revision ID: 35facf49398a
Revises: baf936c59194
Create Date: 2026-06-04 18:42:17.614817

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '35facf49398a'
down_revision = 'baf936c59194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partmovement',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    # movementtype already created in M008; reference it without re-emitting CREATE TYPE.
    sa.Column('event_type', postgresql.ENUM('RECEIVED', 'SOLD', 'MAINTENANCE_OUT', 'PROJECT_OUT', 'ADJUSTED_OUT', name='movementtype', create_type=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('part_batch_id', sa.Uuid(), nullable=True),
    sa.Column('from_location_id', sa.Uuid(), nullable=True),
    sa.Column('to_location_id', sa.Uuid(), nullable=True),
    sa.Column('sale_id', sa.Uuid(), nullable=True),
    sa.Column('service_ticket_id', sa.Uuid(), nullable=True),
    sa.Column('project_pull_id', sa.Uuid(), nullable=True),
    sa.Column('stock_adjustment_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_part_movement_qty_positive'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['part_batch_id'], ['partbatch.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_part_movement_idempotency_key')
    )
    op.create_index('ix_part_movement_product_occurred', 'partmovement', ['product_id', sa.literal_column('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_part_movement_product_occurred', table_name='partmovement')
    op.drop_table('partmovement')
    # ### end Alembic commands ###
