"""M020 sync_review_item

Revision ID: 73a2b0eb6de0
Revises: b043d4fbe95f
Create Date: 2026-06-06 03:17:27.767589

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73a2b0eb6de0'
down_revision = 'b043d4fbe95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syncreviewitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('mutation_kind', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Enum('STALE', 'CONFLICT', name='syncreviewreason'), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'RESOLVED', 'DISCARDED', name='syncreviewstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_syncreviewitem_idempotency_key')
    )
    op.create_index(op.f('ix_syncreviewitem_resolved_by_user_id'), 'syncreviewitem', ['resolved_by_user_id'], unique=False)
    op.create_index('ix_syncreviewitem_state_created', 'syncreviewitem', ['state', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_syncreviewitem_state_created', table_name='syncreviewitem')
    op.drop_index(op.f('ix_syncreviewitem_resolved_by_user_id'), table_name='syncreviewitem')
    op.drop_table('syncreviewitem')
    # Drop the native enum types this migration created, else a re-upgrade fails
    # with "type already exists" (syncreviewreason/syncreviewstate are used only
    # by this table).
    op.execute("DROP TYPE IF EXISTS syncreviewreason")
    op.execute("DROP TYPE IF EXISTS syncreviewstate")
    # ### end Alembic commands ###
