"""M005 product price_change

Revision ID: 79d84d624376
Revises: 57b548cbb28b
Create Date: 2026-06-04 16:06:18.610323

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79d84d624376'
down_revision = '57b548cbb28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('tracking_mode', sa.Enum('SERIALIZED', 'QUANTITY', name='trackingmode'), nullable=False),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retail_price_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('repair_price_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_min_stock_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_table('pricechange',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricechange_product_id'), 'pricechange', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricechange_product_id'), table_name='pricechange')
    op.drop_table('pricechange')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    sa.Enum(name='trackingmode').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
