"""M008_M015 unit + unit_movement serialized ledger

Revision ID: 79e9c3acbe2f
Revises: 91c694abe040
Create Date: 2026-06-04 16:33:13.680980

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '79e9c3acbe2f'
down_revision = '91c694abe040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_serial', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('castranova_barcode', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('current_state', sa.Enum('RECEIVED', 'IN_STOCK', 'SOLD', 'MAINTENANCE_OUT', 'PROJECT_OUT', 'ADJUSTED_OUT', name='unitstate'), nullable=False),
    sa.Column('current_location_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_cost_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('castranova_barcode', name='uq_unit_castranova_barcode'),
    sa.UniqueConstraint('supplier_id', 'supplier_serial', name='uq_unit_supplier_serial')
    )
    op.create_index('ix_unit_state_product', 'unit', ['current_state', 'product_id'], unique=False)
    op.create_table('unitmovement',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('RECEIVED', 'SOLD', 'MAINTENANCE_OUT', 'PROJECT_OUT', 'ADJUSTED_OUT', name='movementtype'), nullable=False),
    sa.Column('from_location_id', sa.Uuid(), nullable=True),
    sa.Column('to_location_id', sa.Uuid(), nullable=True),
    sa.Column('sale_id', sa.Uuid(), nullable=True),
    sa.Column('service_ticket_id', sa.Uuid(), nullable=True),
    sa.Column('project_pull_id', sa.Uuid(), nullable=True),
    sa.Column('stock_adjustment_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_unit_movement_idempotency_key')
    )
    op.create_index('ix_unit_movement_unit_occurred', 'unitmovement', ['unit_id', sa.literal_column('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unit_movement_unit_occurred', table_name='unitmovement')
    op.drop_table('unitmovement')
    op.drop_index('ix_unit_state_product', table_name='unit')
    op.drop_table('unit')
    # CREATE TABLE auto-created these enum types; drop_table does not. Drop them
    # explicitly so a re-upgrade does not fail with "type already exists".
    sa.Enum(name='movementtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='unitstate').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
