"""M-review hardening: drop dup sale idx, received_at NOT NULL

Revision ID: 879329fa7480
Revises: 339478689c73
Create Date: 2026-06-04 17:00:39.533459

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '879329fa7480'
down_revision = '339478689c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_idempotency_key'), table_name='sale')
    op.alter_column('unit', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_sale_idempotency_key'), 'sale', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###
