"""M005b add review indexes

Revision ID: 91c694abe040
Revises: 79d84d624376
Create Date: 2026-06-04 16:18:42.493336

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '91c694abe040'
down_revision = '79d84d624376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pricechange_changed_by_user_id'), 'pricechange', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_product_is_active'), 'product', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_tracking_mode'), 'product', ['tracking_mode'], unique=False)
    op.create_index(op.f('ix_project_customer_id'), 'project', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_customer_id'), table_name='project')
    op.drop_index(op.f('ix_product_tracking_mode'), table_name='product')
    op.drop_index(op.f('ix_product_is_active'), table_name='product')
    op.drop_index(op.f('ix_pricechange_changed_by_user_id'), table_name='pricechange')
    # ### end Alembic commands ###
