"""m017 cost_line fifo consumption split

Revision ID: a76d14af1bf8
Revises: 35facf49398a
Create Date: 2026-06-04 18:48:47.925559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a76d14af1bf8'
down_revision = '35facf49398a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costline',
    sa.Column('part_movement_id', sa.Uuid(), nullable=False),
    sa.Column('part_batch_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0 AND total_cost_thb = quantity * unit_cost_thb', name='ck_cost_line_total'),
    sa.ForeignKeyConstraint(['part_batch_id'], ['partbatch.id'], ),
    sa.ForeignKeyConstraint(['part_movement_id'], ['partmovement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_movement_id', 'part_batch_id', name='uq_cost_line_movement_batch')
    )
    op.create_index('ix_cost_line_part_batch', 'costline', ['part_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cost_line_part_batch', table_name='costline')
    op.drop_table('costline')
    # ### end Alembic commands ###
