"""M023 add dashboard FK indexes

Revision ID: b043d4fbe95f
Revises: 682dcec90af9
Create Date: 2026-06-05 23:53:06.831516

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b043d4fbe95f'
down_revision = '682dcec90af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_partmovement_service_ticket_id', 'partmovement', ['service_ticket_id'], unique=False, postgresql_where=sa.text('service_ticket_id IS NOT NULL'))
    op.create_index('ix_projectpull_customer_id', 'projectpull', ['customer_id'], unique=False)
    op.create_index('ix_projectpull_project_id', 'projectpull', ['project_id'], unique=False)
    op.create_index('ix_sale_customer_id', 'sale', ['customer_id'], unique=False)
    op.create_index('ix_serviceticket_customer_id', 'serviceticket', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_serviceticket_customer_id', table_name='serviceticket')
    op.drop_index('ix_sale_customer_id', table_name='sale')
    op.drop_index('ix_projectpull_project_id', table_name='projectpull')
    op.drop_index('ix_projectpull_customer_id', table_name='projectpull')
    op.drop_index('ix_partmovement_service_ticket_id', table_name='partmovement', postgresql_where=sa.text('service_ticket_id IS NOT NULL'))
    # ### end Alembic commands ###
