"""m009 part_batch quantity fifo stock

Revision ID: baf936c59194
Revises: 879329fa7480
Create Date: 2026-06-04 18:35:17.021447

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'baf936c59194'
down_revision = '879329fa7480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partbatch',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('batch_no', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_batch_ref', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('purchase_cost_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_adjustment', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('received_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('received_qty > 0 AND remaining_qty >= 0 AND remaining_qty <= received_qty', name='ck_part_batch_qty_bounds'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'batch_no', name='uq_part_batch_product_no')
    )
    op.create_index('ix_part_batch_product_remaining', 'partbatch', ['product_id', 'remaining_qty'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_part_batch_product_remaining', table_name='partbatch')
    op.drop_table('partbatch')
    # ### end Alembic commands ###
