"""M013 pricing_override_request

Revision ID: c9a23e6de5d4
Revises: 1cb3d9a4ffc0
Create Date: 2026-06-05 14:38:36.024856

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c9a23e6de5d4'
down_revision = '1cb3d9a4ffc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricingoverriderequest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_kind', sa.Enum('SALE_LINE', 'SERVICE_TICKET_PART', name='overridetargetkind'), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('default_price_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requested_price_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deviation_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('state', sa.Enum('AUTO_APPROVED', 'PENDING', 'APPROVED', 'REJECTED', name='overridestate'), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('default_price_thb >= 0', name='ck_override_default_price_nonneg'),
    sa.CheckConstraint('deviation_pct >= 0', name='ck_override_deviation_nonneg'),
    sa.CheckConstraint('requested_price_thb >= 0', name='ck_override_requested_price_nonneg'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_override_state_created', 'pricingoverriderequest', ['state', 'created_at'], unique=False)
    # Wire the override FK (+ nullable-unique) onto the two consuming lines.
    op.create_unique_constraint('uq_saleline_pricing_override_request_id', 'saleline', ['pricing_override_request_id'])
    op.create_foreign_key('fk_saleline_pricing_override_request_id', 'saleline', 'pricingoverriderequest', ['pricing_override_request_id'], ['id'])
    op.create_unique_constraint('uq_service_ticket_part_pricing_override_request_id', 'serviceticketpart', ['pricing_override_request_id'])
    op.create_foreign_key('fk_service_ticket_part_pricing_override_request_id', 'serviceticketpart', 'pricingoverriderequest', ['pricing_override_request_id'], ['id'])
    # NOTE: pre-existing notificationlog/project_pull_id drift surfaced by
    # autogenerate is intentionally omitted (predates this task).


def downgrade():
    op.drop_constraint('fk_service_ticket_part_pricing_override_request_id', 'serviceticketpart', type_='foreignkey')
    op.drop_constraint('uq_service_ticket_part_pricing_override_request_id', 'serviceticketpart', type_='unique')
    op.drop_constraint('fk_saleline_pricing_override_request_id', 'saleline', type_='foreignkey')
    op.drop_constraint('uq_saleline_pricing_override_request_id', 'saleline', type_='unique')
    op.drop_index('ix_pricing_override_state_created', table_name='pricingoverriderequest')
    op.drop_table('pricingoverriderequest')
