"""m012 project_pull project_pull_line

Revision ID: d40a4b91d505
Revises: 2103c84cc16e
Create Date: 2026-06-04 13:39:37.973469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd40a4b91d505'
down_revision = '2103c84cc16e'
branch_labels = None
depends_on = None

# salelinekind was already created in M010; reference it without re-creating the
# PG type (create_type=False suppresses the inline CREATE TYPE). projectpullstate
# + linestate are new — created with these tables.
salelinekind = postgresql.ENUM(
    'UNIT', 'PART', name='salelinekind', create_type=False
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectpull',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'FULFILLED', 'SHORT', 'CANCELLED', name='projectpullstate'), nullable=False),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_pull_state_created', 'projectpull', ['state', 'created_at'], unique=False)
    op.create_table('projectpullline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_pull_id', sa.Uuid(), nullable=False),
    sa.Column('line_kind', salelinekind, nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('unit_serial', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('requested_qty', sa.Integer(), nullable=True),
    sa.Column('fulfilled_qty', sa.Integer(), nullable=False),
    sa.Column('line_state', sa.Enum('PENDING', 'FULFILLED', 'SHORT', 'CANCELLED', name='linestate'), nullable=False),
    sa.CheckConstraint('requested_qty IS NULL OR requested_qty > 0', name='ck_project_pull_line_requested_qty_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['project_pull_id'], ['projectpull.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectpullline_project_pull_id'), 'projectpullline', ['project_pull_id'], unique=False)
    # ### end Alembic commands ###
    # Wire the FK constraints on the pre-existing bare-nullable project_pull_id
    # columns now that projectpull exists (mirrors M010's sale_id wiring).
    op.create_foreign_key(
        'fk_unitmovement_project_pull_id', 'unitmovement', 'projectpull',
        ['project_pull_id'], ['id']
    )
    op.create_foreign_key(
        'fk_partmovement_project_pull_id', 'partmovement', 'projectpull',
        ['project_pull_id'], ['id']
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_partmovement_project_pull_id', 'partmovement', type_='foreignkey'
    )
    op.drop_constraint(
        'fk_unitmovement_project_pull_id', 'unitmovement', type_='foreignkey'
    )
    op.drop_index(op.f('ix_projectpullline_project_pull_id'), table_name='projectpullline')
    op.drop_table('projectpullline')
    op.drop_index('ix_project_pull_state_created', table_name='projectpull')
    op.drop_table('projectpull')
    # ### end Alembic commands ###
    # Drop the enum types these tables introduced (salelinekind is owned by M010
    # and intentionally left in place).
    sa.Enum(name='linestate').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='projectpullstate').drop(op.get_bind(), checkfirst=True)
