/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTicketsRouteImport } from './routes/_layout/tickets'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSaleRouteImport } from './routes/_layout/sale'
import { Route as LayoutReceiveRouteImport } from './routes/_layout/receive'
import { Route as LayoutPullsRouteImport } from './routes/_layout/pulls'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketsRoute = LayoutTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSaleRoute = LayoutSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReceiveRoute = LayoutReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPullsRoute = LayoutPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/pulls': typeof LayoutPullsRoute
  '/receive': typeof LayoutReceiveRoute
  '/sale': typeof LayoutSaleRoute
  '/settings': typeof LayoutSettingsRoute
  '/tickets': typeof LayoutTicketsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/pulls': typeof LayoutPullsRoute
  '/receive': typeof LayoutReceiveRoute
  '/sale': typeof LayoutSaleRoute
  '/settings': typeof LayoutSettingsRoute
  '/tickets': typeof LayoutTicketsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/pulls': typeof LayoutPullsRoute
  '/_layout/receive': typeof LayoutReceiveRoute
  '/_layout/sale': typeof LayoutSaleRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tickets': typeof LayoutTicketsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/pulls'
    | '/receive'
    | '/sale'
    | '/settings'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/pulls'
    | '/receive'
    | '/sale'
    | '/settings'
    | '/tickets'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/admin'
    | '/_layout/pulls'
    | '/_layout/receive'
    | '/_layout/sale'
    | '/_layout/settings'
    | '/_layout/tickets'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tickets': {
      id: '/_layout/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof LayoutTicketsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sale': {
      id: '/_layout/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof LayoutSaleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/receive': {
      id: '/_layout/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof LayoutReceiveRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pulls': {
      id: '/_layout/pulls'
      path: '/pulls'
      fullPath: '/pulls'
      preLoaderRoute: typeof LayoutPullsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutPullsRoute: typeof LayoutPullsRoute
  LayoutReceiveRoute: typeof LayoutReceiveRoute
  LayoutSaleRoute: typeof LayoutSaleRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTicketsRoute: typeof LayoutTicketsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutPullsRoute: LayoutPullsRoute,
  LayoutReceiveRoute: LayoutReceiveRoute,
  LayoutSaleRoute: LayoutSaleRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTicketsRoute: LayoutTicketsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
