/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTicketsRouteImport } from './routes/_layout/tickets'
import { Route as LayoutSyncReviewRouteImport } from './routes/_layout/sync-review'
import { Route as LayoutSuppliersRouteImport } from './routes/_layout/suppliers'
import { Route as LayoutStockAdjustmentRouteImport } from './routes/_layout/stock-adjustment'
import { Route as LayoutStockRouteImport } from './routes/_layout/stock'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutSaleRouteImport } from './routes/_layout/sale'
import { Route as LayoutReceiveRouteImport } from './routes/_layout/receive'
import { Route as LayoutPullsRouteImport } from './routes/_layout/pulls'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutProductsRouteImport } from './routes/_layout/products'
import { Route as LayoutPricingOverridesRouteImport } from './routes/_layout/pricing-overrides'
import { Route as LayoutOverrideExceptionsRouteImport } from './routes/_layout/override-exceptions'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutLowStockRouteImport } from './routes/_layout/low-stock'
import { Route as LayoutHoldingPeriodRouteImport } from './routes/_layout/holding-period'
import { Route as LayoutChannelMarginRouteImport } from './routes/_layout/channel-margin'
import { Route as LayoutAuditRouteImport } from './routes/_layout/audit'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProjectProjectIdRouteImport } from './routes/_layout/project.$projectId'
import { Route as LayoutCustomerCustomerIdRouteImport } from './routes/_layout/customer.$customerId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketsRoute = LayoutTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSyncReviewRoute = LayoutSyncReviewRouteImport.update({
  id: '/sync-review',
  path: '/sync-review',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSuppliersRoute = LayoutSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStockAdjustmentRoute = LayoutStockAdjustmentRouteImport.update({
  id: '/stock-adjustment',
  path: '/stock-adjustment',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStockRoute = LayoutStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSaleRoute = LayoutSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReceiveRoute = LayoutReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPullsRoute = LayoutPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPricingOverridesRoute = LayoutPricingOverridesRouteImport.update({
  id: '/pricing-overrides',
  path: '/pricing-overrides',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOverrideExceptionsRoute =
  LayoutOverrideExceptionsRouteImport.update({
    id: '/override-exceptions',
    path: '/override-exceptions',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLowStockRoute = LayoutLowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHoldingPeriodRoute = LayoutHoldingPeriodRouteImport.update({
  id: '/holding-period',
  path: '/holding-period',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChannelMarginRoute = LayoutChannelMarginRouteImport.update({
  id: '/channel-margin',
  path: '/channel-margin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditRoute = LayoutAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectProjectIdRoute = LayoutProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomerCustomerIdRoute =
  LayoutCustomerCustomerIdRouteImport.update({
    id: '/customer/$customerId',
    path: '/customer/$customerId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/audit': typeof LayoutAuditRoute
  '/channel-margin': typeof LayoutChannelMarginRoute
  '/holding-period': typeof LayoutHoldingPeriodRoute
  '/low-stock': typeof LayoutLowStockRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/override-exceptions': typeof LayoutOverrideExceptionsRoute
  '/pricing-overrides': typeof LayoutPricingOverridesRoute
  '/products': typeof LayoutProductsRoute
  '/projects': typeof LayoutProjectsRoute
  '/pulls': typeof LayoutPullsRoute
  '/receive': typeof LayoutReceiveRoute
  '/sale': typeof LayoutSaleRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/stock': typeof LayoutStockRoute
  '/stock-adjustment': typeof LayoutStockAdjustmentRoute
  '/suppliers': typeof LayoutSuppliersRoute
  '/sync-review': typeof LayoutSyncReviewRoute
  '/tickets': typeof LayoutTicketsRoute
  '/customer/$customerId': typeof LayoutCustomerCustomerIdRoute
  '/project/$projectId': typeof LayoutProjectProjectIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/audit': typeof LayoutAuditRoute
  '/channel-margin': typeof LayoutChannelMarginRoute
  '/holding-period': typeof LayoutHoldingPeriodRoute
  '/low-stock': typeof LayoutLowStockRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/override-exceptions': typeof LayoutOverrideExceptionsRoute
  '/pricing-overrides': typeof LayoutPricingOverridesRoute
  '/products': typeof LayoutProductsRoute
  '/projects': typeof LayoutProjectsRoute
  '/pulls': typeof LayoutPullsRoute
  '/receive': typeof LayoutReceiveRoute
  '/sale': typeof LayoutSaleRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/stock': typeof LayoutStockRoute
  '/stock-adjustment': typeof LayoutStockAdjustmentRoute
  '/suppliers': typeof LayoutSuppliersRoute
  '/sync-review': typeof LayoutSyncReviewRoute
  '/tickets': typeof LayoutTicketsRoute
  '/': typeof LayoutIndexRoute
  '/customer/$customerId': typeof LayoutCustomerCustomerIdRoute
  '/project/$projectId': typeof LayoutProjectProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/audit': typeof LayoutAuditRoute
  '/_layout/channel-margin': typeof LayoutChannelMarginRoute
  '/_layout/holding-period': typeof LayoutHoldingPeriodRoute
  '/_layout/low-stock': typeof LayoutLowStockRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/override-exceptions': typeof LayoutOverrideExceptionsRoute
  '/_layout/pricing-overrides': typeof LayoutPricingOverridesRoute
  '/_layout/products': typeof LayoutProductsRoute
  '/_layout/projects': typeof LayoutProjectsRoute
  '/_layout/pulls': typeof LayoutPullsRoute
  '/_layout/receive': typeof LayoutReceiveRoute
  '/_layout/sale': typeof LayoutSaleRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/stock': typeof LayoutStockRoute
  '/_layout/stock-adjustment': typeof LayoutStockAdjustmentRoute
  '/_layout/suppliers': typeof LayoutSuppliersRoute
  '/_layout/sync-review': typeof LayoutSyncReviewRoute
  '/_layout/tickets': typeof LayoutTicketsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/customer/$customerId': typeof LayoutCustomerCustomerIdRoute
  '/_layout/project/$projectId': typeof LayoutProjectProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/audit'
    | '/channel-margin'
    | '/holding-period'
    | '/low-stock'
    | '/notifications'
    | '/override-exceptions'
    | '/pricing-overrides'
    | '/products'
    | '/projects'
    | '/pulls'
    | '/receive'
    | '/sale'
    | '/search'
    | '/settings'
    | '/stock'
    | '/stock-adjustment'
    | '/suppliers'
    | '/sync-review'
    | '/tickets'
    | '/customer/$customerId'
    | '/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/audit'
    | '/channel-margin'
    | '/holding-period'
    | '/low-stock'
    | '/notifications'
    | '/override-exceptions'
    | '/pricing-overrides'
    | '/products'
    | '/projects'
    | '/pulls'
    | '/receive'
    | '/sale'
    | '/search'
    | '/settings'
    | '/stock'
    | '/stock-adjustment'
    | '/suppliers'
    | '/sync-review'
    | '/tickets'
    | '/'
    | '/customer/$customerId'
    | '/project/$projectId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/admin'
    | '/_layout/audit'
    | '/_layout/channel-margin'
    | '/_layout/holding-period'
    | '/_layout/low-stock'
    | '/_layout/notifications'
    | '/_layout/override-exceptions'
    | '/_layout/pricing-overrides'
    | '/_layout/products'
    | '/_layout/projects'
    | '/_layout/pulls'
    | '/_layout/receive'
    | '/_layout/sale'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/stock'
    | '/_layout/stock-adjustment'
    | '/_layout/suppliers'
    | '/_layout/sync-review'
    | '/_layout/tickets'
    | '/_layout/'
    | '/_layout/customer/$customerId'
    | '/_layout/project/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tickets': {
      id: '/_layout/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof LayoutTicketsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sync-review': {
      id: '/_layout/sync-review'
      path: '/sync-review'
      fullPath: '/sync-review'
      preLoaderRoute: typeof LayoutSyncReviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/suppliers': {
      id: '/_layout/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof LayoutSuppliersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stock-adjustment': {
      id: '/_layout/stock-adjustment'
      path: '/stock-adjustment'
      fullPath: '/stock-adjustment'
      preLoaderRoute: typeof LayoutStockAdjustmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stock': {
      id: '/_layout/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof LayoutStockRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sale': {
      id: '/_layout/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof LayoutSaleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/receive': {
      id: '/_layout/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof LayoutReceiveRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pulls': {
      id: '/_layout/pulls'
      path: '/pulls'
      fullPath: '/pulls'
      preLoaderRoute: typeof LayoutPullsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pricing-overrides': {
      id: '/_layout/pricing-overrides'
      path: '/pricing-overrides'
      fullPath: '/pricing-overrides'
      preLoaderRoute: typeof LayoutPricingOverridesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/override-exceptions': {
      id: '/_layout/override-exceptions'
      path: '/override-exceptions'
      fullPath: '/override-exceptions'
      preLoaderRoute: typeof LayoutOverrideExceptionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/low-stock': {
      id: '/_layout/low-stock'
      path: '/low-stock'
      fullPath: '/low-stock'
      preLoaderRoute: typeof LayoutLowStockRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/holding-period': {
      id: '/_layout/holding-period'
      path: '/holding-period'
      fullPath: '/holding-period'
      preLoaderRoute: typeof LayoutHoldingPeriodRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/channel-margin': {
      id: '/_layout/channel-margin'
      path: '/channel-margin'
      fullPath: '/channel-margin'
      preLoaderRoute: typeof LayoutChannelMarginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit': {
      id: '/_layout/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof LayoutAuditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/project/$projectId': {
      id: '/_layout/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof LayoutProjectProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/customer/$customerId': {
      id: '/_layout/customer/$customerId'
      path: '/customer/$customerId'
      fullPath: '/customer/$customerId'
      preLoaderRoute: typeof LayoutCustomerCustomerIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAuditRoute: typeof LayoutAuditRoute
  LayoutChannelMarginRoute: typeof LayoutChannelMarginRoute
  LayoutHoldingPeriodRoute: typeof LayoutHoldingPeriodRoute
  LayoutLowStockRoute: typeof LayoutLowStockRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutOverrideExceptionsRoute: typeof LayoutOverrideExceptionsRoute
  LayoutPricingOverridesRoute: typeof LayoutPricingOverridesRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
  LayoutProjectsRoute: typeof LayoutProjectsRoute
  LayoutPullsRoute: typeof LayoutPullsRoute
  LayoutReceiveRoute: typeof LayoutReceiveRoute
  LayoutSaleRoute: typeof LayoutSaleRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStockRoute: typeof LayoutStockRoute
  LayoutStockAdjustmentRoute: typeof LayoutStockAdjustmentRoute
  LayoutSuppliersRoute: typeof LayoutSuppliersRoute
  LayoutSyncReviewRoute: typeof LayoutSyncReviewRoute
  LayoutTicketsRoute: typeof LayoutTicketsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCustomerCustomerIdRoute: typeof LayoutCustomerCustomerIdRoute
  LayoutProjectProjectIdRoute: typeof LayoutProjectProjectIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAuditRoute: LayoutAuditRoute,
  LayoutChannelMarginRoute: LayoutChannelMarginRoute,
  LayoutHoldingPeriodRoute: LayoutHoldingPeriodRoute,
  LayoutLowStockRoute: LayoutLowStockRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutOverrideExceptionsRoute: LayoutOverrideExceptionsRoute,
  LayoutPricingOverridesRoute: LayoutPricingOverridesRoute,
  LayoutProductsRoute: LayoutProductsRoute,
  LayoutProjectsRoute: LayoutProjectsRoute,
  LayoutPullsRoute: LayoutPullsRoute,
  LayoutReceiveRoute: LayoutReceiveRoute,
  LayoutSaleRoute: LayoutSaleRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStockRoute: LayoutStockRoute,
  LayoutStockAdjustmentRoute: LayoutStockAdjustmentRoute,
  LayoutSuppliersRoute: LayoutSuppliersRoute,
  LayoutSyncReviewRoute: LayoutSyncReviewRoute,
  LayoutTicketsRoute: LayoutTicketsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCustomerCustomerIdRoute: LayoutCustomerCustomerIdRoute,
  LayoutProjectProjectIdRoute: LayoutProjectProjectIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
